### ISSUE TITLE
WinPhone8 branch, Kobo upstream fixes

### ISSUE THREAD

**Issue by danielweck** [readium/readium-sdk#113]
Readium:
https://github.com/readium/readium-sdk/tree/WinPhone8

Kobo:
https://github.com/kobolabs/readium-sdk/tree/Kobo_WinPhone8

There are important upstream bug fixes, such as:
https://github.com/kobolabs/readium-sdk/commit/86a9ca40c83c86d5880f2bed2402020a57633d1f#diff-08c8ca4a8f9f5a85c520f78828e7f7aaR379

...compare with:
https://github.com/readium/readium-sdk/blob/WinPhone8/ePub3/xml/utilities/io_win.cpp#L373

There's probably more to hunt for. Needs a cleanup / sync.

**Comment by rkwright** [comment]
Who cares about WinPhone 8 at this point? Closing as obsolete
