### ISSUE TITLE
Evaluate new Android tool chain

### ISSUE THREAD

**Issue by rkwright** [readium/readium-sdk#129]
SDK is currently being developed with the standard Adroid ADT bundle and NDK.  This works, but isn't optimal, particularly because the C++ support isn't great.  The editor support (syntax checking, code optimization, syntax coloring, etc.) are not great.  In addition, debugging into the C++ from Java can be done but is somewhat cumbersome.

Alternatively, there is Android Studio and other IDEs being developed, but it isn't obvious that they are better.  After we reach the 1.0 (m1.1) milestone we should evaluate other options.

**Comment by danielweck** [comment]
The old Eclipse model is deprecated (by Google), now replaced with Android Studio IDE +Gradle build system. The pull requests have been merged into the develop branch.
