### ISSUE TITLE
HTTP Byte Range Requests Fail on Android

### ISSUE THREAD

**Issue by rkwright** [readium/readium-sdk#150]
From Daniel:

However, Media Overlays audio fails to play, it looks like the problem
comes from HTTP byte range requests.

Juan, have you ever been able to play MOs in your branch?

Logcat excerpt quoted below: I see NumberFormatException for
incomplete range syntax "BEGIN-", and more importantly
java.net.SocketException: sendto failed: EPIPE (Broken pipe). Also,
later: Fatal signal 11 (SIGSEGV)

As you can see from the media backend user-agent string
('stagefright/1.2 (Linux;Android 4.4.4)'), I am running KitKat (note
that I have the ART runtime activated).

Dan

sendto failed: EPIPE (Broken pipe)
12-18 01:17:48.734: E/Response(27600): java.net.SocketException:
sendto failed: EPIPE (Broken pipe)
12-18 01:17:48.734: E/Response(27600): at
libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:499)
12-18 01:17:48.734: E/Response(27600): at
libcore.io.IoBridge.sendto(IoBridge.java:468)
12-18 01:17:48.734: E/Response(27600): at
java.net.PlainSocketImpl.write(PlainSocketImpl.java:508)
12-18 01:17:48.734: E/Response(27600): at
java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:46)
12-18 01:17:48.734: E/Response(27600): at
java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:270)
12-18 01:17:48.734: E/Response(27600): at
fi.iki.elonen.NanoHTTPD$Response.send(NanoHTTPD.java:629)
12-18 01:17:48.734: E/Response(27600): at
fi.iki.elonen.NanoHTTPD$Response.access$0(NanoHTTPD.java:585)
12-18 01:17:48.734: E/Response(27600): at
fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:809)
12-18 01:17:48.734: E/Response(27600): at
fi.iki.elonen.NanoHTTPD$1$1.run(NanoHTTPD.java:189)
12-18 01:17:48.734: E/Response(27600): at java.lang.Thread.run(Thread.java:811)
12-18 01:17:48.734: E/Response(27600): Caused by:
libcore.io.ErrnoException: sendto failed: EPIPE (Broken pipe)
12-18 01:17:48.734: E/Response(27600): at
libcore.io.Posix.sendtoBytes(Native Method)
12-18 01:17:48.734: E/Response(27600): at
libcore.io.Posix.sendto(Posix.java:156)
12-18 01:17:48.734: E/Response(27600): at
libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:177)
12-18 01:17:48.734: E/Response(27600): at
libcore.io.IoBridge.sendto(IoBridge.java:466)
12-18 01:17:48.734: E/Response(27600): ... 8 more
12-18 01:17:48.746: E/NanoHTTPD(27600): Socket closed
12-18 01:17:48.980: D/EpubServer(27600): GET
'/audio/ladybuggirl_makes_friends.m4a'
12-18 01:17:48.980: D/EpubServer(27600):   HDR: 'user-agent' =
'stagefright/1.2 (Linux;Android 4.4.4)'
12-18 01:17:48.988: D/EpubServer(27600):   HDR: 'connection' = 'keep-alive'
12-18 01:17:48.988: D/EpubServer(27600):   HDR: 'accept-encoding' =
'gzip,deflate'
12-18 01:17:48.996: D/EpubServer(27600):   HDR: 'host' = 'localhost:8080'
12-18 01:17:48.996: D/EpubServer(27600):   HDR: 'range' = 'bytes=523860-'
12-18 01:17:48.996: D/libepub3
[./../../Platform/Android/jni/jni/jni_ptr.cpp:203](27600):
PointerPool::get(): got pointer 44274934(3) package
[./../../Platform/Android/jni/epub3.cpp:453]
12-18 01:17:48.996: D/libepub3
[./../../Platform/Android/jni/jni/jni_ptr.cpp:203](27600):
PointerPool::get(): got pointer 47E715EC(2) container
[./../../Platform/Android/jni/epub3.cpp:442]
12-18 01:17:49.011: E/EpubServer(27600): NumberFormatException: Invalid long: ""

12-18 01:23:56.078: I/art(27600): GcCauseBackground partial concurrent
mark sweep GC freed 304(13KB) AllocSpace objects, 0(0B) LOS objects,
26% free, 10MB/14MB, paused 887us total 123.728ms
12-18 01:23:56.429: D/EpubServer(27600): GET '/audio/fmse004b.mp3'
12-18 01:23:56.449: D/EpubServer(27600):   HDR: 'user-agent' =
'stagefright/1.2 (Linux;Android 4.4.4)'
12-18 01:23:56.449: D/EpubServer(27600):   HDR: 'connection' = 'keep-alive'
12-18 01:23:56.449: D/EpubServer(27600):   HDR: 'accept-encoding' =
'gzip,deflate'
12-18 01:23:56.461: D/EpubServer(27600):   HDR: 'host' = 'localhost:8080'
12-18 01:23:56.465: D/EpubServer(27600):   HDR: 'range' = 'bytes=6291328-'
12-18 01:23:56.465: D/libepub3
[./../../Platform/Android/jni/jni/jni_ptr.cpp:203](27600):
PointerPool::get(): got pointer 47E51C34(3) package
[./../../Platform/Android/jni/epub3.cpp:453]
12-18 01:23:56.472: D/libepub3
[./../../Platform/Android/jni/jni/jni_ptr.cpp:203](27600):
PointerPool::get(): got pointer 484978FC(2) container
[./../../Platform/Android/jni/epub3.cpp:442]
12-18 01:23:56.492: E/EpubServer(27600): NumberFormatException: Invalid long: ""
12-18 01:23:56.496: I/libepub3
[./../../Platform/Android/jni/packagejni.cpp:764](27600):
Package.nativeInputStreamForRelativePath(): received relative path
'audio/fmse004b.mp3'
12-18 01:23:56.496: D/libepub3
[./../../Platform/Android/jni/jni/jni_ptr.cpp:203](27600):
PointerPool::get(): got pointer 47E51C34(3) package
[./../../Platform/Android/jni/epub3.cpp:453]
12-18 01:23:56.496: I/libepub3
[./../../Platform/Android/jni/packagejni.cpp:766](27600):
Package.nativeInputStreamForRelativePath(): package base path 'OPS/'
12-18 01:23:56.496: I/libepub3
[./../../Platform/Android/jni/packagejni.cpp:768](27600):
Package.nativeInputStreamForRelativePath(): final path
'OPS/audio/fmse004b.mp3'
12-18 01:23:56.496: D/libepub3
[./../../Platform/Android/jni/jni/jni_ptr.cpp:203](27600):
PointerPool::get(): got pointer 484978FC(2) container
[./../../Platform/Android/jni/epub3.cpp:442]
12-18 01:23:56.496: D/libepub3
[./../../Platform/Android/jni/jni/jni_ptr.cpp:203](27600):
PointerPool::get(): got pointer 47E51C34(3) package
[./../../Platform/Android/jni/epub3.cpp:453]
12-18 01:23:56.500: D/libepub3
[./../../Platform/Android/jni/jni/jni_ptr.cpp:203](27600):
PointerPool::get(): got pointer 47E51C34(3) package
[./../../Platform/Android/jni/epub3.cpp:453]
12-18 01:23:56.500: D/libepub3
[./../../Platform/Android/jni/jni/jni_ptr.cpp:203](27600):
PointerPool::get(): got pointer 47E51C34(3) package
[./../../Platform/Android/jni/epub3.cpp:453]
12-18 01:23:56.504: D/libepub3
[./../../Platform/Android/jni/jni/jni_method.h:366](27600):
StaticMethod(): calling static method
'createResourceInputStream[(J)Lorg/readium/sdk/android/util/ResourceInputStream;]'
12-18 01:23:56.511: E/Response(27600): sendto failed: EPIPE (Broken pipe)
12-18 01:23:56.511: E/Response(27600): java.net.SocketException:
sendto failed: EPIPE (Broken pipe)
12-18 01:23:56.511: E/Response(27600): at
libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:499)
12-18 01:23:56.511: E/Response(27600): at
libcore.io.IoBridge.sendto(IoBridge.java:468)
12-18 01:23:56.511: E/Response(27600): at
java.net.PlainSocketImpl.write(PlainSocketImpl.java:508)
12-18 01:23:56.511: E/Response(27600): at
java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:46)
12-18 01:23:56.511: E/Response(27600): at
java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:270)
12-18 01:23:56.511: E/Response(27600): at
fi.iki.elonen.NanoHTTPD$Response.send(NanoHTTPD.java:629)
12-18 01:23:56.511: E/Response(27600): at
fi.iki.elonen.NanoHTTPD$Response.access$0(NanoHTTPD.java:585)
12-18 01:23:56.511: E/Response(27600): at
fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:809)
12-18 01:23:56.511: E/Response(27600): at
fi.iki.elonen.NanoHTTPD$1$1.run(NanoHTTPD.java:189)
12-18 01:23:56.511: E/Response(27600): at java.lang.Thread.run(Thread.java:811)
12-18 01:23:56.511: E/Response(27600): Caused by:
libcore.io.ErrnoException: sendto failed: EPIPE (Broken pipe)
12-18 01:23:56.511: E/Response(27600): at
libcore.io.Posix.sendtoBytes(Native Method)
12-18 01:23:56.511: E/Response(27600): at
libcore.io.Posix.sendto(Posix.java:156)
12-18 01:23:56.511: E/Response(27600): at
libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:177)
12-18 01:23:56.511: E/Response(27600): at
libcore.io.IoBridge.sendto(IoBridge.java:466)
12-18 01:23:56.511: E/Response(27600): ... 8 more
12-18 01:23:56.531: E/NanoHTTPD(27600): Socket closed
12-18 01:23:57.285: A/libc(27600): Fatal signal 11 (SIGSEGV) at
0x4f46f000 (code=2), thread 28218 (NanoHttpd Reque)

**Comment by danielweck** [comment]
This was addressed by #50
