### ISSUE TITLE
Android NDK Windows compile fails at #include ePub3/epub3.h (No such file or directory)

### ISSUE THREAD

**Issue by rakanmatouq** [readium/readium-sdk#152]
01-24 22:47:53.603: E/AndroidRuntime(7875): FATAL EXCEPTION: main
01-24 22:47:53.603: E/AndroidRuntime(7875): Process: org.readium.sdk.android.launcher, PID: 7875
01-24 22:47:53.603: E/AndroidRuntime(7875): java.lang.UnsatisfiedLinkError: Couldn't load epub3 from loader dalvik.system.PathClassLoader[dexPath=/data/app/org.readium.sdk.android.launcher-5.apk,libraryPath=/data/app-lib/org.readium.sdk.android.launcher-5]: findLibrary returned null
01-24 22:47:53.603: E/AndroidRuntime(7875): 	at java.lang.Runtime.loadLibrary(Runtime.java:358)
01-24 22:47:53.603: E/AndroidRuntime(7875): 	at java.lang.System.loadLibrary(System.java:526)
01-24 22:47:53.603: E/AndroidRuntime(7875): 	at org.readium.sdk.android.EPub3.<clinit>(EPub3.java:44)
01-24 22:47:53.603: E/AndroidRuntime(7875): 	at org.readium.sdk.android.launcher.ContainerList.onCreate(ContainerList.java:136)
01-24 22:47:53.603: E/AndroidRuntime(7875): 	at android.app.Activity.performCreate(Activity.java:5389)
01-24 22:47:53.603: E/AndroidRuntime(7875): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
01-24 22:47:53.603: E/AndroidRuntime(7875): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2256)
01-24 22:47:53.603: E/AndroidRuntime(7875): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2350)
01-24 22:47:53.603: E/AndroidRuntime(7875): 	at android.app.ActivityThread.access$800(ActivityThread.java:163)
01-24 22:47:53.603: E/AndroidRuntime(7875): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1257)
01-24 22:47:53.603: E/AndroidRuntime(7875): 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-24 22:47:53.603: E/AndroidRuntime(7875): 	at android.os.Looper.loop(Looper.java:157)
01-24 22:47:53.603: E/AndroidRuntime(7875): 	at android.app.ActivityThread.main(ActivityThread.java:5335)
01-24 22:47:53.603: E/AndroidRuntime(7875): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-24 22:47:53.603: E/AndroidRuntime(7875): 	at java.lang.reflect.Method.invoke(Method.java:515)
01-24 22:47:53.603: E/AndroidRuntime(7875): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
01-24 22:47:53.603: E/AndroidRuntime(7875): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
01-24 22:47:53.603: E/AndroidRuntime(7875): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by danielweck** [comment]
Hello, it looks like the underlying native library is not generated yet, and consequently not included in the Eclipse build. Open your command line shell, go to readium-sdk/platform/Android/ and run "ndk-compile.sh build /Applications/android-ndk" (or wherever your NDK is installed).
Alternatively, use Eclipse to enable the project builder for ndk-compile.sh, but bare in mind that it will run every time you rebuild the JNI library project...and that's time-consuming.

**Comment by rakanmatouq** [comment]
Hello @danielweck 

i know the thing about NDK , i tried doing it on cmd but i couldnt run the ./ file , i downloaded cygwin but it didnt compile it either :/ what should i do ?

Thanks

**Comment by danielweck** [comment]
Ah Windows...
What happens when you run the simple command `ndk-compile.sh` or `./ndk-compile.sh` or `sh ndk-compile.sh`?

**Comment by rakanmatouq** [comment]
ndk-compile.sh : Opens the "Open with" prompt
and both ./ and sh gives : ' ' is not recognized as an internal or external command , operable program or batch file

**Comment by danielweck** [comment]
Is Bash installed in Cygwin?

**Comment by rakanmatouq** [comment]
$ ./ndk-compile.sh build C:/Users/Rakan/Downloads/readium-sdk-master/android-ndk                                                                                                                                                 -r10d
Starting ndk-build...

Project path: /cygdrive/c/Users/Rakan/Downloads/readium-sdk-master/readium-sdk-m                                                                                                                                                 aster/Platform/Android
NDK path: C:/Users/Rakan/Downloads/readium-sdk-master/android-ndk-r10d
Command: build

./MakeHeaders.sh: Platform/Android/MakeHeaders.sh: /bin/zsh: bad interpreter: Pe                                                                                                                                                 rmission denied
/cygdrive/c/Users/Rakan/Downloads/readium-sdk-master/readium-sdk-master/Platform                                                                                                                                                 /Android
make: Entering directory '/cygdrive/c/Users/Rakan/Downloads/readium-sdk-master/r                                                                                                                                                 eadium-sdk-master/Platform/Android'
Android NDK: WARNING: APP_PLATFORM android-19 is larger than android:minSdkVersi                                                                                                                                                 on 11 in /cygdrive/c/Users/Rakan/Downloads/readium-sdk-master/readium-sdk-master                                                                                                                                                 /Platform/Android/AndroidManifest.xml
/cygdrive/c/Users/Rakan/Downloads/readium-sdk-master/android-ndk-r10d/build/core                                                                                                                                                 /build-binary.mk:457: warning: overriding recipe for target '/cygdrive/c/Users/R                                                                                                                                                 akan/Downloads/readium-sdk-master/readium-sdk-master/Platform/Android/obj/local/                                                                                                                                                 armeabi-v7a/objs/epub3/ePub3/ePub/property_extension.o'
/cygdrive/c/Users/Rakan/Downloads/readium-sdk-master/android-ndk-r10d/build/core                                                                                                                                                 /build-binary.mk:457: warning: ignoring old recipe for target '/cygdrive/c/Users                                                                                                                                                 /Rakan/Downloads/readium-sdk-master/readium-sdk-master/Platform/Android/obj/loca                                                                                                                                                 l/armeabi-v7a/objs/epub3/ePub3/ePub/property_extension.o'
/cygdrive/c/Users/Rakan/Downloads/readium-sdk-master/android-ndk-r10d/build/core                                                                                                                                                 /build-binary.mk:457: warning: overriding recipe for target '/cygdrive/c/Users/R                                                                                                                                                 akan/Downloads/readium-sdk-master/readium-sdk-master/Platform/Android/obj/local/                                                                                                                                                 armeabi-v7a/objs/epub3/Platform/Android/jni/android/backup_atomics.o'
/cygdrive/c/Users/Rakan/Downloads/readium-sdk-master/android-ndk-r10d/build/core                                                                                                                                                 /build-binary.mk:457: warning: ignoring old recipe for target '/cygdrive/c/Users                                                                                                                                                 /Rakan/Downloads/readium-sdk-master/readium-sdk-master/Platform/Android/obj/loca                                                                                                                                                 l/armeabi-v7a/objs/epub3/Platform/Android/jni/android/backup_atomics.o'
/cygdrive/c/Users/Rakan/Downloads/readium-sdk-master/android-ndk-r10d/build/core                                                                                                                                                 /build-binary.mk:457: warning: overriding recipe for target '/cygdrive/c/Users/R                                                                                                                                                 akan/Downloads/readium-sdk-master/readium-sdk-master/Platform/Android/obj/local/                                                                                                                                                 armeabi-v7a/objs/epub3/Platform/Android/jni/jni/jni_ptr.o'
/cygdrive/c/Users/Rakan/Downloads/readium-sdk-master/android-ndk-r10d/build/core                                                                                                                                                 /build-binary.mk:457: warning: ignoring old recipe for target '/cygdrive/c/Users                                                                                                                                                 /Rakan/Downloads/readium-sdk-master/readium-sdk-master/Platform/Android/obj/loca                                                                                                                                                 l/armeabi-v7a/objs/epub3/Platform/Android/jni/jni/jni_ptr.o'
/cygdrive/c/Users/Rakan/Downloads/readium-sdk-master/android-ndk-r10d/build/core                                                                                                                                                 /build-binary.mk:457: warning: overriding recipe for target '/cygdrive/c/Users/R                                                                                                                                                 akan/Downloads/readium-sdk-master/readium-sdk-master/Platform/Android/obj/local/                                                                                                                                                 armeabi-v7a/objs/epub3/Platform/Android/jni/epub3.o'
/cygdrive/c/Users/Rakan/Downloads/readium-sdk-master/android-ndk-r10d/build/core                                                                                                                                                 /build-binary.mk:457: warning: ignoring old recipe for target '/cygdrive/c/Users                                                                                                                                                 /Rakan/Downloads/readium-sdk-master/readium-sdk-master/Platform/Android/obj/loca                                                                                                                                                 l/armeabi-v7a/objs/epub3/Platform/Android/jni/epub3.o'
/cygdrive/c/Users/Rakan/Downloads/readium-sdk-master/android-ndk-r10d/build/core                                                                                                                                                 /build-binary.mk:457: warning: overriding recipe for target '/cygdrive/c/Users/R                                                                                                                                                 akan/Downloads/readium-sdk-master/readium-sdk-master/Platform/Android/obj/local/                                                                                                                                                 armeabi-v7a/objs/epub3/Platform/Android/jni/container.o'
/cygdrive/c/Users/Rakan/Downloads/readium-sdk-master/android-ndk-r10d/build/core                                                                                                                                                 /build-binary.mk:457: warning: ignoring old recipe for target '/cygdrive/c/Users                                                                                                                                                 /Rakan/Downloads/readium-sdk-master/readium-sdk-master/Platform/Android/obj/loca                                                                                                                                                 l/armeabi-v7a/objs/epub3/Platform/Android/jni/container.o'
/cygdrive/c/Users/Rakan/Downloads/readium-sdk-master/android-ndk-r10d/build/core                                                                                                                                                 /build-binary.mk:457: warning: overriding recipe for target '/cygdrive/c/Users/R                                                                                                                                                 akan/Downloads/readium-sdk-master/readium-sdk-master/Platform/Android/obj/local/                                                                                                                                                 armeabi-v7a/objs/epub3/Platform/Android/jni/iri.o'
/cygdrive/c/Users/Rakan/Downloads/readium-sdk-master/android-ndk-r10d/build/core                                                                                                                                                 /build-binary.mk:457: warning: ignoring old recipe for target '/cygdrive/c/Users                                                                                                                                                 /Rakan/Downloads/readium-sdk-master/readium-sdk-master/Platform/Android/obj/loca                                                                                                                                                 l/armeabi-v7a/objs/epub3/Platform/Android/jni/iri.o'
/cygdrive/c/Users/Rakan/Downloads/readium-sdk-master/android-ndk-r10d/build/core                                                                                                                                                 /build-binary.mk:457: warning: overriding recipe for target '/cygdrive/c/Users/R                                                                                                                                                 akan/Downloads/readium-sdk-master/readium-sdk-master/Platform/Android/obj/local/                                                                                                                                                 armeabi-v7a/objs/epub3/Platform/Android/jni/resource_stream.o'
/cygdrive/c/Users/Rakan/Downloads/readium-sdk-master/android-ndk-r10d/build/core                                                                                                                                                 /build-binary.mk:457: warning: ignoring old recipe for target '/cygdrive/c/Users                                                                                                                                                 /Rakan/Downloads/readium-sdk-master/readium-sdk-master/Platform/Android/obj/loca                                                                                                                                                 l/armeabi-v7a/objs/epub3/Platform/Android/jni/resource_stream.o'
Android NDK: WARNING:Android.mk:xml2: LOCAL_LDLIBS is always ignored for static                                                                                                                                                  libraries
rm -f /cygdrive/c/Users/Rakan/Downloads/readium-sdk-master/readium-sdk-master/Pl                                                                                                                                                 atform/Android/libs/arm64-v8a/lib*.so /cygdrive/c/Users/Rakan/Downloads/readium-                                                                                                                                                 sdk-master/readium-sdk-master/Platform/Android/libs/armeabi/lib*.so /cygdrive/c/                                                                                                                                                 Users/Rakan/Downloads/readium-sdk-master/readium-sdk-master/Platform/Android/lib                                                                                                                                                 s/armeabi-v7a/lib*.so /cygdrive/c/Users/Rakan/Downloads/readium-sdk-master/readi                                                                                                                                                 um-sdk-master/Platform/Android/libs/armeabi-v7a-hard/lib*.so /cygdrive/c/Users/R                                                                                                                                                 akan/Downloads/readium-sdk-master/readium-sdk-master/Platform/Android/libs/mips/                                                                                                                                                 lib*.so /cygdrive/c/Users/Rakan/Downloads/readium-sdk-master/readium-sdk-master/                                                                                                                                                 Platform/Android/libs/mips64/lib*.so /cygdrive/c/Users/Rakan/Downloads/readium-s                                                                                                                                                 dk-master/readium-sdk-master/Platform/Android/libs/x86/lib*.so /cygdrive/c/Users                                                                                                                                                 /Rakan/Downloads/readium-sdk-master/readium-sdk-master/Platform/Android/libs/x86                                                                                                                                                 _64/lib*.so
rm -f /cygdrive/c/Users/Rakan/Downloads/readium-sdk-master/readium-sdk-master/Pl                                                                                                                                                 atform/Android/libs/arm64-v8a/gdbserver /cygdrive/c/Users/Rakan/Downloads/readiu                                                                                                                                                 m-sdk-master/readium-sdk-master/Platform/Android/libs/armeabi/gdbserver /cygdriv                                                                                                                                                 e/c/Users/Rakan/Downloads/readium-sdk-master/readium-sdk-master/Platform/Android                                                                                                                                                 /libs/armeabi-v7a/gdbserver /cygdrive/c/Users/Rakan/Downloads/readium-sdk-master                                                                                                                                                 /readium-sdk-master/Platform/Android/libs/armeabi-v7a-hard/gdbserver /cygdrive/c                                                                                                                                                 /Users/Rakan/Downloads/readium-sdk-master/readium-sdk-master/Platform/Android/li                                                                                                                                                 bs/mips/gdbserver /cygdrive/c/Users/Rakan/Downloads/readium-sdk-master/readium-s                                                                                                                                                 dk-master/Platform/Android/libs/mips64/gdbserver /cygdrive/c/Users/Rakan/Downloa                                                                                                                                                 ds/readium-sdk-master/readium-sdk-master/Platform/Android/libs/x86/gdbserver /cy                                                                                                                                                 gdrive/c/Users/Rakan/Downloads/readium-sdk-master/readium-sdk-master/Platform/An                                                                                                                                                 droid/libs/x86_64/gdbserver
rm -f /cygdrive/c/Users/Rakan/Downloads/readium-sdk-master/readium-sdk-master/Pl                                                                                                                                                 atform/Android/libs/arm64-v8a/gdb.setup /cygdrive/c/Users/Rakan/Downloads/readiu                                                                                                                                                 m-sdk-master/readium-sdk-master/Platform/Android/libs/armeabi/gdb.setup /cygdriv                                                                                                                                                 e/c/Users/Rakan/Downloads/readium-sdk-master/readium-sdk-master/Platform/Android                                                                                                                                                 /libs/armeabi-v7a/gdb.setup /cygdrive/c/Users/Rakan/Downloads/readium-sdk-master                                                                                                                                                 /readium-sdk-master/Platform/Android/libs/armeabi-v7a-hard/gdb.setup /cygdrive/c                                                                                                                                                 /Users/Rakan/Downloads/readium-sdk-master/readium-sdk-master/Platform/Android/li                                                                                                                                                 bs/mips/gdb.setup /cygdrive/c/Users/Rakan/Downloads/readium-sdk-master/readium-s                                                                                                                                                 dk-master/Platform/Android/libs/mips64/gdb.setup /cygdrive/c/Users/Rakan/Downloa                                                                                                                                                 ds/readium-sdk-master/readium-sdk-master/Platform/Android/libs/x86/gdb.setup /cy                                                                                                                                                 gdrive/c/Users/Rakan/Downloads/readium-sdk-master/readium-sdk-master/Platform/An                                                                                                                                                 droid/libs/x86_64/gdb.setup
[armeabi-v7a] Compile++ thumb: epub3 <= resource_stream.cpp
/cygdrive/c/Users/Rakan/Downloads/readium-sdk-master/android-ndk-r10d/toolchains                                                                                                                                                 /arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-g++                                                                                                                                                  -MMD -MP -MF C:/Users/Rakan/Downloads/readium-sdk-master/readium-sdk-master/Pla                                                                                                                                                 tform/Android/obj/local/armeabi-v7a/objs/epub3/Platform/Android/jni/resource_str                                                                                                                                                 eam.o.d.org -fpic -ffunction-sections -funwind-tables -fstack-protector -no-cano                                                                                                                                                 nical-prefixes -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -fno-exceptions                                                                                                                                                  -fno-rtti -mthumb -Os -g -DNDEBUG -fomit-frame-pointer -fno-strict-aliasing -fi                                                                                                                                                 nline-limit=64 -Iinclude -I./../../ePub3 -I./../../ePub3/utilities -I./../../ePu                                                                                                                                                 b3/xml -I./../../ePub3/xml/tree -I./../../ePub3/xml/utilities -I./../../ePub3/xm                                                                                                                                                 l/validation -I./../../ePub3/ePub -I./../../Platform/Android/jni -I./../../Platf                                                                                                                                                 orm/Android/jni/android -I./../../ePub3/ThirdParty/openssl-android/include -I./.                                                                                                                                                 ./../ePub3/ThirdParty/boost/include -IC:/Users/Rakan/Downloads/readium-sdk-maste                                                                                                                                                 r/android-ndk-r10d/sources/cxx-stl/gnu-libstdc++/4.9/include -IC:/Users/Rakan/Do                                                                                                                                                 wnloads/readium-sdk-master/android-ndk-r10d/sources/cxx-stl/gnu-libstdc++/4.9/li                                                                                                                                                 bs/armeabi-v7a/include -IC:/Users/Rakan/Downloads/readium-sdk-master/android-ndk                                                                                                                                                 -r10d/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -I./../../ePub3/ThirdPa                                                                                                                                                 rty/icu4c/include -I./../../ePub3/ThirdParty/icu4c/include -I./../../ePub3/Third                                                                                                                                                 Party/icu4c/include -I./../../ePub3/ThirdParty/icu4c/include -I./../.. -DANDROID                                                                                                                                                  -std=gnu11 -include prefix.h -DBUILDING_EPUB3 -Wa,--noexecstack -Wformat -Werro                                                                                                                                                 r=format-security -std=gnu++11 -include prefix.h -fpermissive -DBUILDING_EPUB3 -                                                                                                                                                 frtti -fexceptions -std=gnu++11 -include prefix.h -fpermissive -DBUILDING_EPUB3                                                                                                                                                     -IC:/Users/Rakan/Downloads/readium-sdk-master/android-ndk-r10d/platforms/andr                                                                                                                                                 oid-19/arch-arm/usr/include -c  ./../../Platform/Android/jni/resource_stream.cpp                                                                                                                                                  -o C:/Users/Rakan/Downloads/readium-sdk-master/readium-sdk-master/Platform/Andr                                                                                                                                                 oid/obj/local/armeabi-v7a/objs/epub3/Platform/Android/jni/resource_stream.o && /                                                                                                                                                 cygdrive/c/Users/Rakan/Downloads/readium-sdk-master/readium-sdk-master/Platform/                                                                                                                                                 Android/obj/convert-dependencies.sh C:/Users/Rakan/Downloads/readium-sdk-master/                                                                                                                                                 readium-sdk-master/Platform/Android/obj/local/armeabi-v7a/objs/epub3/Platform/An                                                                                                                                                 droid/jni/resource_stream.o.d
cc1plus.exe: warning: command line option '-std=gnu11' is valid for C/ObjC but n                                                                                                                                                 ot for C++
In file included from ./../../Platform/Android/jni/resource_stream.cpp:27:0:
./../../ePub3/utilities/byte_stream.h:24:25: fatal error: ePub3/epub3.h: No such                                                                                                                                                  file or directory
 #include <ePub3/epub3.h>
                         ^
compilation terminated.
/cygdrive/c/Users/Rakan/Downloads/readium-sdk-master/android-ndk-r10d/build/core                                                                                                                                                 /build-binary.mk:457: recipe for target '/cygdrive/c/Users/Rakan/Downloads/readi                                                                                                                                                 um-sdk-master/readium-sdk-master/Platform/Android/obj/local/armeabi-v7a/objs/epu                                                                                                                                                 b3/Platform/Android/jni/resource_stream.o' failed
make: *** [/cygdrive/c/Users/Rakan/Downloads/readium-sdk-master/readium-sdk-mast                                                                                                                                                 er/Platform/Android/obj/local/armeabi-v7a/objs/epub3/Platform/Android/jni/resour                                                                                                                                                 ce_stream.o] Error 1
make: Leaving directory '/cygdrive/c/Users/Rakan/Downloads/readium-sdk-master/re                                                                                                                                                 adium-sdk-master/Platform/Android'

**Comment by rakanmatouq** [comment]
sorry if its too long

**Comment by danielweck** [comment]
Oh, now it's working? Great! How did you solve the shell script issue? (Windows command line with PowerShell or Cygwin?)

As for the error below:

```
./../../ePub3/utilities/byte_stream.h:24:25: fatal error: ePub3/epub3.h: No such file or directory
#include 
```
https://github.com/readium/readium-sdk/blob/develop/ePub3/utilities/byte_stream.h#L24

The header file definitely exists, so I'm not sure what's going on?

https://github.com/readium/readium-sdk/blob/develop/ePub3/ePub/epub3.h

**Comment by danielweck** [comment]
Re-opening with different title.

**Comment by rakanmatouq** [comment]
i reinstalled cygwin and used it to compile the .sh file ...

so whats the problem now ? :D

**Comment by danielweck** [comment]
(renamed title to explicitly mention Android NDK, specifically on MS Windows)

**Comment by rakanmatouq** [comment]
thanks :+1:

**Comment by danielweck** [comment]
See here:
https://github.com/readium/SDKLauncher-Android/issues/12#issuecomment-74860384
