### ISSUE TITLE
Performances questions

### ISSUE THREAD

**Issue by Twibit** [readium/readium-sdk#157]
I would like to increase the performances of my android application because the rendering is a bit slow.

What can i do to optimize the page loading speed ? 
Is it possible to use an unzipped epub instead of an archive ?
Is there any recommandations on how to create the epub file in order to have the best reading performances ?

**Comment by danielweck** [comment]
Hi @Twibit I assume your main target platform is Android? (judging by the bug report about the 1-second page loading delay: https://github.com/readium/SDKLauncher-Android/issues/52 )

Irrespective of your target platform, ReadiumSDK is primarily designed and tested to process EPUB publications directly from the zip archive (on-the-fly inflate / decompression). You might be able to refactor the architecture (e.g. abstract the filesystem access API), but I'm not sure that the implementation costs would justify the benefits. In other words, I don't think that "live unzipping" is cause for any serious performance bottleneck.

On the application level, an HTTP server is used to supply content resources to the WebView. Although this is required for audio/video streaming (byte range support), strictly-speaking other types of assets can be served via a URL request interception, or another URL scheme handler (protocol). However, I very much doubt that this would make a substantial difference.

Now, what about the WebView itself? With reflowable documents, there is an initial reset of the CSS font size (to match user preferences) which requires potentially-costly DOM mutations. Perhaps disabling the code in `UpdateHtmlFontSize` would help?
https://github.com/readium/readium-shared-js/blob/develop/js/helpers.js#L99

Do you observe slow rendering with pre-paginated / fixed-layout EPUBs too?

Thanks!

**Comment by rkwright** [comment]
@Twibit:  Seems like a really good first approach would be to try and profile some of your typical EPUBs.

http://stackoverflow.com/questions/3871311/how-can-i-profile-my-android-app

http://developer.android.com/tools/debugging/debugging-tracing.html

This would constitute an awesome contribution to Readium, BTW.

**Comment by Twibit** [comment]
I'm on Android but we are working on multiple platforms.

Our performance issue occurs when we have an epub containing more than 10k files (because of  HTML5 animations). It is slow even if the page to load is a simple image (FL).
I have modified the HTTP server to supply files from an unzipped directory instead of the epub file and it is two time faster than from the archive. The drawback is that i need a lot more disk space (epub + unzipped files).

**Comment by rkwright** [comment]
@twibit Hm.  Might it make sense to create a tool that merges the HTML5 animations so they aren't separate files?  But perhaps that is impractical (not knowing a thing about your EPUBs).  Is it possible to share one of your EPUBs?

**Comment by Twibit** [comment]
I don't produce any epub so i can't make optimisations... And I can't share it.

But the problem seems to be related to the number of file. 
Access times are good with a 800Mo epub with few but large files.
Access times are bad with a 800Mo epub filled with tiny files.

**Comment by danielweck** [comment]
Ah, great number of files, that makes more sense to me now. Despite the lack of "real" network latency in the local HTTP server (ping), there is of course a cost overhead in each established connection.

**Comment by rkwright** [comment]
Hm.  Hate to say this, but it may turn out that this is simply a case of bad practice by the publisher.  Ultimately, one can always produce an EPUB (or PDF) that performs poorly.  How does iBooks perform with these EPUBs on the iPad?

**Comment by danielweck** [comment]
I've seen many fixed-layout / prepaginated EPUBs exported from InDesign with tons of duplicated files for each HTML spine item (FXL page), and lots of framework Javascript code (like Adobe Edge).

**Comment by Twibit** [comment]
@danielweck Yeah, that is probably one of those. But the bad access times occurs even if we load a single file.
@rkwright I don't know but it works fine with readium-js-viewer on a Surface Pro

**Comment by danielweck** [comment]
@Twibit oh sure, single zipped EPUB file, but many distinct HTTP requests behind the scenes, one for each WebView resource. Also, I wonder about the libzip I/O cost each time a file handle is opened/closed. I guess it depends on the target platform.

**Comment by danielweck** [comment]
@Twibit you mentioned readium-js-viewer, but do you mean Chrome extension (i.e. already-expanded EPUBs), or cloud reader (i.e. either already-unzipped EPUBs, or still-compressed EPUB archives)?

In the case of cloud reader with zipped EPUBs, the default ZIP "file system" prototype is extended with support for HTTP byte range requests:

https://github.com/readium/readium-js/blob/develop/lib/zip-fs.js#L488

**Comment by Twibit** [comment]
@danielweck No ! The page i'm displaying is composed of a simple HTML file and a background image (2 HTTP requests). For the same page in an epub containing 100 other file, or in an epub containing 10k+ files, the data access time is different.

I was talking about the chrome extension embeded in a windows store app (already-expanded EPUBs so there isn't any access time problem).

**Comment by danielweck** [comment]
@Twibit okay that's interesting. This suggests a performance issue in the libzip library then (fseek?). I wonder if the libzip update made by LearningAlly (Tom McCartney's team) brings benefits other than support for large media files?

**Comment by rkwright** [comment]
Note that I did NOT integrate the new LibZip.  It IS integrated into the master branch version of the Windows Launcher. That branch includes the whole readium-sdk repo - not as a submodule.  So there is still a task to take the work that LA did there and replace the version that is in mainline readium-sdk.  I took a quick look when I did the initial work to replace it with submodules, but it was clear it wasn't going to be a trivial copy and past operation.
A volunteer would be welcome.

**Comment by danielweck** [comment]
This issue seems resolved (based on the discussion thread). I am sure there is plenty of scope for further performance improvements (notably in terms of page rendering / font-loading latency, etc.), but for that we need more concrete / narrow problem descriptions. Let's close this issue, feel free to open new ones.
