### ISSUE TITLE
ContentFilter, non-ByteRange case, no need for BytesAvailable() override, use NeedsCache capability (prefetch media resource, whole byte buffer.length)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-sdk#163]
`NeedsCache` (must be set to truye always, because HTTP byte-range case is never encountered when `filter_chain_byte_stream` is instantiated):
https://github.com/readium/readium-sdk/blob/develop/ePub3/ePub/filter_chain_byte_stream.cpp#L61

`BytesAvailable()`:
https://github.com/readium/readium-sdk/blob/develop/ePub3/ePub/filter_chain_byte_stream.h#L66

https://docs.google.com/document/d/11NZEzDQhNesEfN6jXZTAihnC7XgFIrCTOT5TVkL0-P4/edit

**Comment by nleme** [comment]
I wrote a document that describes the whole issue, plus the proposed fix. In addition, it also contains the scenarios where this would come into play, and how the proposed fix would work with it. It is saved as a Google Doc:

https://docs.google.com/document/d/1rB3LO0-aUuFxTbxSrc44gFzvL7zMh3-LFYpUnFskPAU/edit#

**Comment by danielweck** [comment]
Pretty thorough @nleme (as always!) Many thanks!
I believe you have already started implementation, so I hope you don't mind if I assign you to this issue.

**Comment by danielweck** [comment]
Feature branch: https://github.com/readium/readium-sdk/tree/feature/contentLengthFixes

**Comment by nleme** [comment]
I made two commits in the feature branch "feature/contentLengthFixes" to implement the fix for this issue. I list the two commits below:

https://github.com/readium/readium-sdk/commit/4dd27db0cd110e3d88cb4e56537f4fe7fb5cda67

https://github.com/readium/readium-sdk/commit/cddeb6787a5739dbc6ebfd4e102f28a5cf2d8d1e

I'll be waiting until release 18 is out the door before merging this code into develop.

**Comment by nleme** [comment]
I just opened a pull request to merge the changes from "feature/contentLengthFixes" (which were made in the two commits quoted in my previous comment) into develop. The pull request is:

https://github.com/readium/readium-sdk/pull/169
