### ISSUE TITLE
AGPL License and iOS Appstore

### ISSUE THREAD

**Issue by Zwergal** [readium/readium-sdk#164]
This project seems very promising, but isn't there a licensing issue if you want to include the SDK in an iOS App which should be distributed in the Appstore? You can't submit an App licensed under the GPL in the Appstore as far as I know? Is there a possibility to get a commercial license so one can include the SDK in a commercial App which should not be open-source and licensed with the GPL?

**Comment by danielweck** [comment]
Hello @Zwergal 

Most of Readium's codebase (e.g. Javascript libraries) is subject to a permissive BSD opens-source license, but the C++ Readium SDK is dual-licensed (see http://readium.org/license-readium-sdk ):
- GNU Affero General Public License (AGPL) v3
or:
- by arrangement under an Apache-based alternative licensing agreement, see http://readium.org/about-us/corporate-documents/readium-sdk-license

Additionally, there's an Individual Contributor License Agreement (ICLA) in place to facilitate participation from individuals, corporations etc. See http://readium.org/licenses/icla

@rkwright am I getting this right? ;)

**Comment by Zwergal** [comment]
Ah I see. Thanks for the links. But 30.000$ is a whole lot of money. Hoped it would be cheaper...

**Comment by rkwright** [comment]
Yes, this is correct.

**Comment by danielweck** [comment]
@rkwright should this issue title be renamed, to better describe what the problem is? Also, this strikes me as a Readium governance / policy -related discussion, not something that developers can help solve here.

**Comment by rkwright** [comment]
I have in fact raised it at the board level, trying to get some clarity on a couple of points.  Let's just leave it for the moment.
