### ISSUE TITLE
WKWebView window.parent/top = self, new epubReadingSystem method, requires changing deep iframe injection routine

### ISSUE THREAD

**Issue by danielweck** [readium/readium-sdk#166]
See:
https://github.com/readium/readium-sdk/commit/669659c2e63129b818ce13c88709fc446c776e10#commitcomment-10473931

**Comment by danielweck** [comment]
Copy from above link:

At line 316 below (`NSString *inject_epubReadingSystem1`)
https://github.com/readium/readium-sdk/blob/feature/wkwebview/Platform/Apple/RDServices/Main/RDPackageResourceConnection.m#L316

...we can set `window.parent/top` to `window` immediately after `window.readium_set_epubReadingSystem = undefined;`, which should be a satisfactory method to plug the iframe sandboxing security hole. Just as we do in the Chrome extension and the cloud reader:
https://github.com/readium/readium-js/blob/develop/epub-modules/Readium.js#L36
https://github.com/readium/readium-js-viewer/blob/develop/chrome-app/epubReadingSystem.js
```
navigator.epubReadingSystem = window.parent.navigator.epubReadingSystem;
window.parent = window.self;
window.top = window.self;
```

However, we must remember to adjust the "deep iframe injection" method, so that iframes within EPUB Content Documents (e.g. widgets / EPUB3 Embedded Scriptable Components) can still access `window.parent.postMessage()`:
https://github.com/readium/readium-sdk/blob/feature/wkwebview/Platform/Apple/RDServices/Main/RDPackageResourceConnection.m#L207
Maybe we can just pass an additional boolean parameter to the
`readium_set_epubReadingSystem()` function, set to true for the root
iframe, false for any descendant iframe.

```
NSString* cmd = @"var epubRSInject = function(win)
{
if (win.frames)
{
for (var i = 0; i < win.frames.length; i++)
{
var iframe = win.frames[i];
if (iframe.readium_set_epubReadingSystem)
{
iframe.readium_set_epubReadingSystem(window.navigator.epubReadingSystem);
}
epubRSInject(iframe);
}
}
};

epubRSInject(window);";
```

**Comment by rkwright** [comment]
Good point @danielweck   Thanks for catching this.

**Comment by danielweck** [comment]
This was addressed in this commit: https://github.com/readium/readium-sdk/commit/41d0770bceaa2e63c6ce511f8a76289d9f551e85
