### ISSUE TITLE
Can you supply an drmed epub file?

### ISSUE THREAD

**Issue by wzhsunn** [readium/readium-sdk#170]
I want to make an drmed epub or found one when open it in iBooks report "drmed file" .

**Comment by danielweck** [comment]
Hello, there are several DRM / encryption schemes, none of which Readium (the reading system) handles specifically. In other words, this issue tracker (software bugs) is not the right place to ask for DRM'ed EPUBs. I suggest you ask this question on the IDPF forum, or even the MobileRead forums.
