### ISSUE TITLE
Is the readium lcp open source ?

### ISSUE THREAD

**Issue by wzhsunn** [readium/readium-sdk#171]
if so, where is source ?

thank you !

**Comment by danielweck** [comment]
There is no open-source LCP software available to the public at the Readium GitHub. However, there is a specification effort conducted by a dedicated working group, so this may be of interest to you. I believe they have some internal encoding software (server-side) to test the specification. Please reach out to them directly to find out more. You might need to become a Readium Foundation member, I am not sure:
http://readium.org/projects/readium-lcp
(LCP  is a separate activity, outside of EPUB3 / IDPF)

**Comment by rkwright** [comment]
If you are interested in participating in the LCP activities, please contact me directly at rkwright@readium.org and I can put you in contact with the group.

**Comment by pgstath** [comment]
Hi @rkwright, I am having the same question with  @wzhsunn, should I follow the same procedure? Are there any updates about LCP ?

**Comment by danielweck** [comment]
@pgstath I think that we will hear more about LCP within the next few weeks, both in terms of specification status and implementations. There are a few open-source proposals on GitHub, but no code formally endorsed by Readium just yet (under https://github.com/readium).

**Comment by pgstath** [comment]
Hi @danielweck, thanks for the information, good news!
