### ISSUE TITLE
Possible collision between EPUB error codes and Windows error codes

### ISSUE THREAD

**Issue by nleme** [readium/readium-sdk#173]
If you look at the file error_handler.h, you will see that there is a list of error codes for possible EPUB errors. Most of them describe errors in which the book in question is not following something from the EPUB 3 specification.

In addition to that, if you look at the bottom of the file, you will find the following macro definition:

#if EPUB_PLATFORM(WIN)
# define _THROW_WIN_ERROR_(err) HandleError(static_cast<int>(err), std::system_category())
# define _THROW_LAST_ERROR_() _THROW_WIN_ERROR_(::GetLastError())
#endif

Something similar to this can be found in many many Windows programs. It is just a macro to deal with the very common GetLastError() pattern from Windows.

The problem, though, is that if anybody in Windows uses this, you can have a collision between Windows errors and EPUB errors. For example, if some Windows code in Readium gets the following error:

ERROR_BAD_FILE_TYPE

The value of that error is 0xDE, which corresponds to 222. However, the EPUBError enumeration defines 222 as "OPFMissingSpineIdref" ("Spine <itemref> MUST have an idref attribute. Critical."). So a Windows error could be interpreted as an EPUB error, and the wrong error message may be shown to the user (plus the confusion for the poor developer trying to debug this).

This is a small issue, but I thought it would be a good idea to have it documented, just in case the Windows developers start seeing weird errors all of sudden.

One possible solution is to adopt another pattern that has been used in many other Windows applications. Given that we have the whole range of integers available to us as error codes, in the case of a Windows error, the code could simply add 20,000 (for example) so that we would define that errors on 20,000 and above are Windows errors. This way, "OPFMissingSpineIdref" would correspond to 222, whereas ERROR_BAD_FILE_TYPE would be 20,222.

**Comment by AlanQuatermain** [comment]
This is where the category comes in: all Windows errors should be placed into std::system_category(), while EPUB errors are in epub3::epub_category() (I think...)

**Comment by AlanQuatermain** [comment]
Correction: EPUB errors should be in the category returned from epub3::epub_spec_category().

**Comment by danielweck** [comment]
Note that the "error handler" callback functions registered in iOS, OSX, and Android launchers filter messages based on the `is_spec_error()` boolean, which obviously is false for 
`std::system_error` (which is triggered for `std::system_category()`).

See:

`error_details(const std::system_error& __sysErr)`
https://github.com/readium/readium-sdk/blob/develop/ePub3/utilities/error_handler.h#L445
`__DispatchError(const std::system_error& __err)`
https://github.com/readium/readium-sdk/blob/develop/ePub3/utilities/error_handler.h#L517
`HandleError(int __code, const std::error_category& __cat)`
https://github.com/readium/readium-sdk/blob/develop/ePub3/utilities/error_handler.h#L530
`_THROW_WIN_ERROR_(err) HandleError(static_cast<int>(err), std::system_category())`
https://github.com/readium/readium-sdk/blob/develop/ePub3/utilities/error_handler.h#L585

See launcher app -specific "error handlers":

iOS:
https://github.com/readium/readium-sdk/blob/develop/Platform/Apple/RDServices/Main/RDContainer.mm#L68
```
		ePub3::ErrorHandlerFn sdkErrorHandler = ^(const ePub3::error_details& err) {

			const char * msg = err.message();

			BOOL isSevereEpubError = NO;
			if (err.is_spec_error()
					&& (err.severity() == ePub3::ViolationSeverity::Critical
					|| err.severity() == ePub3::ViolationSeverity::Major))
				isSevereEpubError = YES;

			BOOL res = [m_delegate container:self handleSdkError:[NSString stringWithUTF8String:msg] isSevereEpubError:isSevereEpubError];

			return (res == YES ? true : false);
			//return ePub3::DefaultErrorHandler(err);
		};
		ePub3::SetErrorHandler(sdkErrorHandler);
```

OSX:
https://github.com/readium/SDKLauncher-OSX/blob/develop/LauncherOSX/LOXePubSdkApi.mm#L62
```
bool LauncherErrorHandler(const ePub3::error_details& err)
{
    const char * msg = err.message();
    NSLog(@"%s\n", msg);


    if (err.is_spec_error())
    {
        switch ( err.severity() )
        {
            case ePub3::ViolationSeverity::Critical:
            case ePub3::ViolationSeverity::Major: {

                if (m_ignoreRemainingErrors != YES)
                {
                    NSAlert *alert = [[NSAlert alloc] init];
                    [alert setMessageText:@"EPUB warning:"];
                    [alert setInformativeText:[NSString stringWithUTF8String:msg]];

                    [alert addButtonWithTitle:@"Ignore"];
                    [alert addButtonWithTitle:@"Ignore all"];
                    switch ([alert runModal]) {
                        case NSAlertFirstButtonReturn: {
                            // Dismiss
                            break;
                        }
                        case NSAlertSecondButtonReturn: {
                            // Ignore all
                            m_ignoreRemainingErrors = YES;
                            break;
                        }
                        default:
                            break;
                    }
                }

                break;
            }
            default:
                break;
        }
    }

    return true;
    // never throws an exception
    //return ePub3::DefaultErrorHandler(err);
}
ePub3::ErrorHandlerFn launcherErrorHandler = LauncherErrorHandler;
ePub3::SetErrorHandler(launcherErrorHandler);
```

Android:
https://github.com/readium/readium-sdk/blob/develop/Platform/Android/src/org/readium/sdk/android/SdkErrorHandler.java
https://github.com/readium/readium-sdk/blob/develop/Platform/Android/src/org/readium/sdk/android/EPub3.java#L157
https://github.com/readium/readium-sdk/blob/develop/Platform/Android/jni/epub3.cpp#L222
```
static bool LauncherErrorHandler(const ePub3::error_details& err)
{
    const char * msg = err.message();

	bool isSevereEpubError = (err.is_spec_error()
			&& (err.severity() == ePub3::ViolationSeverity::Critical
			|| err.severity() == ePub3::ViolationSeverity::Major));

    LOGD("READIUM SDK ERROR HANDLER (%s): %s\n", isSevereEpubError ? "warning" : "info", msg);

    jstring jmessage = m_env->NewStringUTF(msg);
    jboolean b = javaEPub3_handleSdkError(m_env, jmessage, (jboolean)isSevereEpubError);
    m_env->DeleteLocalRef(jmessage);
    return (bool)b;
    
    // never throws an exception
    //return ePub3::DefaultErrorHandler(err);
}
```
```
    public static SdkErrorHandler m_SdkErrorHandler = null;
    public static void setSdkErrorHandler(SdkErrorHandler sdkErrorHandler) {
        m_SdkErrorHandler = sdkErrorHandler;
    }

	private static boolean handleSdkError(String message, boolean isSevereEpubError) {
        if (m_SdkErrorHandler != null) {
            return m_SdkErrorHandler.handleSdkError(message, isSevereEpubError);
        }
            
        System.out.println("!SdkErrorHandler: " + message + " (" + (isSevereEpubError ? "warning" : "info") + ")");

    	// never throws an exception
    	return true;
	}
```

**Comment by nleme** [comment]
So, the crux of the issue is that, in Windows, whoever is writing the RDServices layer for Windows and also its launcher, must always check the method error_details::is_spec_error() (or error_details::is_system_error()) in order to differentiate between the EPUBError enumeration and one of the Windows errors.

We are doing the right thing in iOS and Android, as we can see above. I must confess that I don't know in which state the RDServices layer and/or the Windows launcher is, therefore I don't know if they are making that check there.

I wonder if a better idea here would be to make completely separate classes here (like SystemError and EPUBError) so that there is no way to get both things confused here. However, given that there is a way to avoid a collision now, I don't think that we need to change the code. As such, I'm marking this issue as closed.
