### ISSUE TITLE
Can't build the SDK

### ISSUE THREAD

**Issue by AshrafTawfeeq** [readium/readium-sdk#176]
Hi all,

I have seen that the issue was opened twice #16 and #48. But still I can't get the SDK working. I have cloned the repo successfully but there's something with the shell command. All I am having is 10 errors and managed to get them 9.

Here's are the issues:
PhaseScriptExecution Run\ Script /Users/ashraftawfeeq/Library/Developer/Xcode/DerivedData/SDKLauncher-iOS-fddhuibvzrciskeriqrbggnvbcbl/Build/Intermediates/ePub3.build/Debug-iphoneos/ePub3-iOS.build/Script-AB5D1071172AD540001D3C95.sh
    cd "/Users/ashraftawfeeq/Desktop/Reader Samples/Readium/readium-sdk/Platform/Apple"
    /bin/sh -c /Users/ashraftawfeeq/Library/Developer/Xcode/DerivedData/SDKLauncher-iOS-fddhuibvzrciskeriqrbggnvbcbl/Build/Intermediates/ePub3.build/Debug-iphoneos/ePub3-iOS.build/Script-AB5D1071172AD540001D3C95.sh

MakeHeaders.sh: line 23: local: can only be used in a function
mkdir: : No such file or directory
MakeHeaders.sh: line 26: typeset: -A: invalid option
typeset: usage: typeset [-afFirtx] [-p] name[=value] ...
ls: ePub3/ThirdParty/utf8-cpp/include/*: No such file or directory
ls: ePub3/ThirdParty/google-url/base/*.h: No such file or directory
ls: ePub3/ThirdParty/google-url/src/*.h: No such file or directory
ls: ePub3/ThirdParty/libzip/*.h: No such file or directory
ls: ePub3/xml/**/*.h: No such file or directory
MakeHeaders.sh: line 30: ePub3/xml: division by 0 (error token is "l")
ls: ePub3/utilities/*.h: No such file or directory
ls: ePub3/utilities/*.inl: No such file or directory
MakeHeaders.sh: line 31: ePub3/utilities: division by 0 (error token is "s")
ls: ePub3/*.h: No such file or directory
MakeHeaders.sh: line 46: ${(k)groups}: bad substitution

![screen shot 2015-05-25 at 14 31 54](https://cloud.githubusercontent.com/assets/8795081/7797306/26e337dc-02f3-11e5-8ed1-795cbb2ee898.png)

**Comment by danielweck** [comment]
`zsh` missing? See https://github.com/readium/readium-sdk/issues/47
