### ISSUE TITLE
Cannot compile new ContentFilter error architecture code in Android

### ISSUE THREAD

**Issue by nleme** [readium/readium-sdk#182]
In the feature/contentFilterErrorArchitecture branch, I checked in a new architecture which provides a way for ContentFilters to report errors to an app that uses the Readium SDK.

Among other things, that architecture uses a type which is defined as a std::function class to a specific type of function. The definition is as such (filter.h, line 53):

typedef std::function<void(const std::string &, unsigned int code, const std::string &)> ContentFilterErrorHandlerFn;

Then, inside the ContentFilter class, we define the following static member variable:

static ContentFilterErrorHandlerFn s_contentFilterErrorHandler;

Then, later inside ContentFilter, we define the following member functions:

    static void ResetContentFilterErrorHandler(ContentFilterErrorHandlerFn contentFilterErrorHandler)
    {
        s_contentFilterErrorHandler = contentFilterErrorHandler;
    }
    
    static void HandleContentFilterError(const std::string &filterId, unsigned int errorCode, const std::string &message)
    {
    	s_contentFilterErrorHandler(filterId, errorCode, message); // <=== Here is where the compiler error happens
    }

    static void HandleContentFilterError(const std::string &filterId, ContentFilterError error, const std::string &message)
        {
            HandleContentFilterError(filterId, (unsigned int)error, message);
        }

I'm trying to compile this in Eclipse, for Android. When I try to compile the code above, the first function (ResetContentFilterErrorHandler) compiles absolutely fine. However, the second function (HandleContentFilterError) does not compile. Eclipse shows the following error:

include/ePub3/filter.h:404: error: undefined reference to 'ePub3::ContentFilter::s_contentFilterErrorHandler'

I have tried my best to find out what is going on here, without success. I researched online, and I could not find anything about Eclipse having a problem with the std::function class. I'm currently stuck at this.

**Comment by nleme** [comment]
Another piece of information that I forgot to include. The above pieces of code compile absolutely fine in Xcode. Whatever is happening here, it does not affect Xcode.

**Comment by JCCR** [comment]
@nleme 
Looks like it fails during linking with this error.
The fix is to add `filter.cpp` in Android.mk

**Comment by nleme** [comment]
Oh, sorry, I forgot to add a detail. I'm really sorry.

Yes, I forgot to talk about that. This started because I was trying to add filter.cpp to the Android project file. I did so, but, after doing that, I started hitting the error that I described above.

**Comment by nleme** [comment]
Let me add another little tidbit of information. I discovered that I can compile if I change the above code to this:

    static void ResetContentFilterErrorHandler(ContentFilterErrorHandlerFn contentFilterErrorHandler)
    {
        s_contentFilterErrorHandler = contentFilterErrorHandler;
    }
    
    static void HandleContentFilterError(const std::string &filterId, unsigned int errorCode, const std::string &message)
    {
    	s_contentFilterErrorHandler(filterId, errorCode, message);
    }

    static void HandleContentFilterError(const std::string &filterId, ContentFilterError error, const std::string &message)
	{
		// HandleContentFilterError(filterId, (unsigned int)error, message);
	}

The only difference is that I commented out the call to HandleContentFilterError() in the second overload of HandleContentFilterError(). I guess that somehow the Eclipse C++ compiler is getting lost in the overloads? I'll keep investigating this to find out how to fix this.

**Comment by JCCR** [comment]
I'm compiling using the ndk-compile.sh script. I haven't gotten the Eclipse C++ method a go yet.

I seem to be building the project without failure here. Can you try building with the script on your end?

I'm going to bring back my Eclipse from the dead in the meantime :)

**Comment by JCCR** [comment]
This was the error I was getting before the Android.mk change:

`./../../ePub3/ePub/PassThroughFilter.cpp:133: error: undefined reference to 'ePub3::ContentFilter::s_contentFilterErrorHandler'`

It looks to be similar to yours, but there's a file and line number reference that leads me to a wrong location?

**Comment by JCCR** [comment]
BTW I'm using the NDK release 19 and my toolchain seems to be using 
```
$NDK/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-g++ --version

arm-linux-androideabi-g++ (GCC) 4.9 20140827 (prerelease)
Copyright (C) 2014 Free Software Foundation, Inc.
```

**Comment by danielweck** [comment]
By "NDK release 19", you mean `Android NDK, Revision 10e (May 2015)`, right?
https://developer.android.com/ndk/downloads/index.html#rel

**Comment by JCCR** [comment]
@nleme @danielweck 
Yea. I meant to say `Android NDK, Revision 10d (December 2014)` :)

**Comment by danielweck** [comment]
I merged `feature/contentFilterErrorArchitecture` ( https://github.com/readium/readium-sdk/tree/feature/contentFilterErrorArchitecture ) into my local working copy of `feature/android-NDK-x86` ( https://github.com/readium/readium-sdk/tree/feature/android-NDK-x86 ), using NDK `r10e` and toolchain `4.9`:

```
$ x86-4.9/prebuilt/windows-x86_64/bin/i686-linux-android-g++ --version
i686-linux-android-g++.exe (GCC) 4.9 20140827 (prerelease)
```

__Successful__ `ndk-compile.sh build` ending with: `[x86] Install        : libepub3.so => libs/x86/libepub3.so`

**Comment by nleme** [comment]
Hi guys,

Just to update this issue, after I completely removed Eclipse and my Android tools, and also the workspace from my machine, and basically started from scratch, I was able to compile fine. No sign whatsoever of the error that was popping up before.

My best guess is that Eclipse can get stuck in a bad state at times.  Completely erasing everything and starting over seems to be the cure in those cases. A number of people have told me that removing the workspace can do the trick too, but I had done that to no avail. So, it seems that sometimes you have to start from scratch.

And here is hope that once we can start using Android Studio, things will be better. :-)
