### ISSUE TITLE
readium-sdk   build warning

### ISSUE THREAD

**Issue by jojoth** [readium/readium-sdk#183]
I'm from thailand I build readium following by  https://docs.google.com/document/d/1DphaTO2fu7mQoBKalzyfphIlOB2Ncp7yHbIbbti92CE/edit#
 It have some warning show some part like 

./../../ePub3/ThirdParty/libxml2-android/xmlmemory.c:276:4: warning: format '%ld' expects argument of type 'long int', but argument 4 has type 'size_t' [-Wformat=]
    "%p : Malloc(%ld) Ok\n", xmlMemTraceBlockAt, size);
    ^
./../../ePub3/ThirdParty/libxml2-android/xmlmemory.c: In function 'xmlReallocLoc':
./../../ePub3/ThirdParty/libxml2-android/xmlmemory.c:352:4: warning: format '%ld' expects argument of type 'long int', but argument 4 has type 'size_t' [-Wformat=]
    xmlMemTraceBlockAt, p->mh_size, size);
    ^
./../../ePub3/ThirdParty/libxml2-android/xmlmemory.c:352:4: warning: format '%ld' expects argument of type 'long int', but argument 5 has type 'size_t' [-Wformat=]

**Comment by danielweck** [comment]
I believe these compiler warning can be ignored safely. The `%ld` format specifier accommodates `size_t` just fine.
