### ISSUE TITLE
Have some error when sync gradle SDKLauncher-Android

### ISSUE THREAD

**Issue by jojoth** [readium/readium-sdk#184]
It show error ::

/Users/pong/Desktop/work/android_proj1/SDKLauncher-Android/ePub3Library/src/main/jni/asm/arch/hardware.h:148:21: fatal error: omap730.h: No such file or directory  #include "omap730.h"

 I search in  [ndk path]/Platform/Android-19/archarm/usr/asm/arch/ . It don't have omap730.h

**Comment by danielweck** [comment]
The old Eclipse model is deprecated (by Google), now replaced with Android Studio IDE +Gradle build system. The pull requests have been merged into the develop branch.
