### ISSUE TITLE
Versioning info not being injected into native Launchers since restructured builds

### ISSUE THREAD

**Issue by rkwright** [readium/readium-sdk#187]
Versioning info is missing from all the NATIVE builds (the JS builds are OK).  When one runs the EPUBReadingSystem epub in the NATIVE launchers, all the version info (sha, etc.) is blank.  Is there some special trick to getting the build process to generate the version info?  I didn’t see it in the release doc.

**Comment by danielweck** [comment]
This was part of the checklist when merging-in the RequireJS / plugins refactoring (and it successfully passed the test). SDK-Launcher `OSX` and `iOS` invoke `epubReadingSystem.sh` via a XCode build task, `Android `via the Eclipse Builder system (maybe this Android build step does not automatically execute anymore?). I will get my OSX machine back on Saturday, at which time I will test again.

**Comment by rkwright** [comment]
@danielweck Thanks for the info.  I'll check it later this morning and see if I can see what's going on.

**Comment by rkwright** [comment]
OK, I see the script and it apparently does run.  In the build log, I see:

     ReadiumSDK.READIUM_OSX_sha = '4269832350f2918f04947ca8b6c8a465b5b0c44c';
     ReadiumSDK.READIUM_OSX_tag = '0.17-41-g4269832';
     ReadiumSDK.READIUM_OSX_clean = 'false';
     ReadiumSDK.READIUM_OSX_version = '0.0.0';
     ReadiumSDK.READIUM_OSX_branch = 'release/0.20';
     ReadiumSDK.READIUM_OSX_release = 'false';
     ReadiumSDK.READIUM_OSX_timestamp = '1438795375';
     ReadiumSDK.READIUM_SDK_sha = '79df79ddb5cbc2e15ae2f8f3b9d30d67a5249679';
     ReadiumSDK.READIUM_SDK_tag = '0.19-0-g79df79d';
     ReadiumSDK.READIUM_SDK_clean = 'true';
     ReadiumSDK.READIUM_SDK_version = '0.0.0';
     ReadiumSDK.READIUM_SDK_branch = 'master release/0.20';
     ReadiumSDK.READIUM_SDK_release = 'false';
     ReadiumSDK.READIUM_SDK_timestamp = '1438795375';
     ReadiumSDK.READIUM_SHARED_JS_sha = 'a35fec93db834bc0f00d37dccec15132730c5b70';
     ReadiumSDK.READIUM_SHARED_JS_tag = '0.18-236-ga35fec9';
     ReadiumSDK.READIUM_SHARED_JS_clean = 'true';
     ReadiumSDK.READIUM_SHARED_JS_version = '0.0.0';
     ReadiumSDK.READIUM_SHARED_JS_branch = 'release/0.20';
     ReadiumSDK.READIUM_SHARED_JS_release = 'false';
     ReadiumSDK.READIUM_SHARED_JS_timestamp = '1438795375';
     ReadiumSDK.READIUM_dateTimeString = 'Wed Aug  5 10:22:55 PDT 2015';

But the output in the Launcher is (only OSX shown)

    epubReadingSystem
    NAME: Readium SDKLauncher-OSX
    VERSION: 1.0.0
    SDKLauncher-OSX
    sha: undefined
    version: undefined
    tag: undefined
    branch: undefined
    release: undefined
    clean: undefined
    timestamp: [undefined] Invalid Date
    url: https://github.com/readium/SDKLauncher-OSX/tree/undefined

**Comment by danielweck** [comment]
I have re-synced my develop branches in iOS, OSX and Android. I cleaned + rebuild the apps, and everything works fine. I am using the `epubReadingSystem.epub` test ebook, which can be found at:

https://github.com/readium/readium-js-viewer/blob/develop/epub_content/epubReadingSystem.epub

https://github.com/readium/SDKLauncher-Android/blob/develop/SDKLauncher-Android/assets/readium-shared-js/epubReadingSystem.epub

https://github.com/readium/SDKLauncher-OSX/blob/develop/LauncherOSX/ReaderScripts/epubReadingSystem.epub

https://github.com/readium/SDKLauncher-iOS/blob/develop/Resources/epubReadingSystem.epub

**Comment by rkwright** [comment]
Well, I rebuilt my develop sandboxes (OSX, iOS) and now I get all the version info correctly.  Going to test the RC repos now.

**Comment by rkwright** [comment]
After resynching to the release/0.20 branch, I get the right results for OSX but not for iOS.  On iOS I still get "undefined" for the version info.  All the submodule refs, etc. look correct.  Still looking at it.

**Comment by danielweck** [comment]
Ric, wrong date format now fixed: https://github.com/readium/readium-sdk/issues/188#issuecomment-130076049

About iOS (your comment above): I manually removed the Readium app from my iPad in order to flush the EPUBs from the app-specific sandboxed storage, then I executed the app from XCode (iPad linked via USB). The `epubReadingSystem.epub` ebook was then updated to the correct latest version (funny pink / yellow colours).

**Comment by danielweck** [comment]
This is an obsolete issue.
