### ISSUE TITLE
Populate custom C++ content filters on-the-fly by host apps, without modifying readium-sdk

### ISSUE THREAD

**Issue by mmenu-mantano** [readium/readium-sdk#203]
Right now we have to modify PopulateFilterManager() in initialization.cpp to remove or add content filters. By nature, content filters are actually plugins and can be created to answer specific host app needs. We shouldn't have to modify Readium sources to add more content filters.

**Comment by danielweck** [comment]
Agreed.
Example with `PassThroughFilter`:
https://github.com/readium/readium-sdk/blob/develop/ePub3/ePub/initialization.cpp#L41
```cpp
void PopulateFilterManager()
{
    static std::once_flag __once;
    std::call_once(__once, []{
        FontObfuscator::Register();
		// If you want to activate the PassThroughFilter (to do testing or debugging),
		// simply uncomment the line below. Also take a look at the file PassThroughFilter.cpp
		// to see if the class is enabling itself.
		//
        // PassThroughFilter::Register();
        SwitchPreprocessor::Register();
        ObjectPreprocessor::Register();
    });
}

```

**Comment by danielweck** [comment]
Was fixed by PR: https://github.com/readium/readium-sdk/pull/204
