### ISSUE TITLE
I Can't compile the Readium successfully.

### ISSUE THREAD

**Issue by zxz1989** [readium/readium-sdk#209]
@danielweck When I operate as you wrrite  in  https://github.com/readium/readium-sdk/issues/168
I Can't compile the Readium successfully.Some errors occured as follow:
![qq 20151020193848](https://cloud.githubusercontent.com/assets/13619754/10606009/4e127938-7762-11e5-96c0-cfa4e7836bf1.png)
How can I correct it?

**Comment by danielweck** [comment]
@zxz1989 hello, I am closing this issue and will reply in the original discussion:
https://github.com/readium/readium-sdk/issues/168
