### ISSUE TITLE
android build fail..

### ISSUE THREAD

**Issue by gibumkim** [readium/readium-sdk#212]
ANDROID is a problem during the build.
Eclipse console message: In file included from ./../../ePub3/xml/utilities/base.cpp:21:0:
./../../ePub3/xml/utilities/base.h:37:29: fatal error: libxml / xmlerror.h: No such file or directory #include ^
Eclipse Problems: Description Resource Path Location Type
fatal error: libxml / xmlerror.h: No such file or directory ePub3-Library line 37 C / C ++ Problem
My os is windows8.
Answers I'll wait...

**Comment by gibumkim** [comment]
ANDROID is a problem during the build.
Eclipse console message: In file included from ./../../ePub3/xml/utilities/base.cpp:21:0:
./../../ePub3/xml/utilities/base.h:37:29: fatal error: libxml / xmlerror.h: No such file or directory #include ^
Eclipse Problems: Description Resource Path Location Type
fatal error: libxml / xmlerror.h: No such file or directory ePub3-Library line 37 C / C ++ Problem
My os is windows8.
Answers I'll wait...

**Comment by huangleon** [comment]
Why closed ?
I still met this problem.
How to resolve it ?

**Comment by huangleon** [comment]
Found it , duplicate of #47

**Comment by danielweck** [comment]
@huangleon also see https://github.com/readium/readium-sdk/issues/47#issuecomment-194145051
