### ISSUE TITLE
Help Eclipse console messages

### ISSUE THREAD

**Issue by gibumkim** [readium/readium-sdk#213]
C:\Users\WorkSpace\Downloads\SDKLauncher-Android-master\readium-sdk\Platform\Android/obj/local/armeabi-v7a/objs-debug/epub3/ePub3/xml/utilities/base.o 
cc1plus.exe: warning: command line option '-std=gnu11' is valid for C/ObjC but not for C++
In file included from ./../../ePub3/xml/utilities/base.cpp:21:0:
./../../ePub3/xml/utilities/base.h:37:29: fatal error: libxml/xmlerror.h: No such file or directory
make.exe: Leaving directory `C:/Users/WorkSpace/Downloads/SDKLauncher-Android-master/readium-sdk/Platform/Android'
 #include <libxml/xmlerror.h>
                             ^
compilation terminated.
make.exe: *** [C:\Users\WorkSpace\Downloads\SDKLauncher-Android-master\readium-sdk\Platform\Android/obj/local/armeabi-v7a/objs-debug/epub3/ePub3/xml/utilities/base.o] Error 1

**** Build Finished ****

**Comment by danielweck** [comment]
Building the Android ReadiumSDK application "launcher" is a bit more difficult than on OSX or Linux, even with Cygwin. I suggest you take a look at the discussion thread in this existing issue:
https://github.com/readium/readium-sdk/issues/180#issuecomment-139166807
Closing as duplicate.

**Comment by gibumkim** [comment]
Thank you very much.

2015-11-06 3:02 GMT+09:00 Daniel Weck <notifications@github.com>:

> Building the Android ReadiumSDK application "launcher" is a bit more
> difficult than on OSX or Linux, even with Cygwin. I suggest you take a look
> at the discussion thread in this existing issue:
> #180 (comment)
> <https://github.com/readium/readium-sdk/issues/180#issuecomment-139166807>
> Closing as duplicate.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/readium/readium-sdk/issues/213#issuecomment-154139155>
> .
>



-- 
*------------------------------*
*INNOVATIS. 김기범*
*E-Mail : gbkim@innovatis.co.kr <bhlee@innovatis.kr>*
* <bhlee@innovatis.kr>**C.P : Tel : 02) 325-2423 / Fax : 02) 324-2427*
*Addr. : **서울시 마포구 잔다리로 73*
*코마빌딩 5층 이노버티스*

**Comment by gibumkim** [comment]
Hello

mReadium JSApi.toggle Media Overlay ();
The method is not play.

locat content
[
12-10 18:43:20.961: I/chromium(10739): [INFO:CONSOLE(0)] "Failed to execute
'play' on 'HTMLMediaElement': API can only be initiated by a user
gesture.", source: file:///android_asset/readium-shared-js/reader.html (0)
]

**Comment by gibumkim** [comment]
logcat image add

2015-12-10 18:45 GMT+09:00 김기범 <gbkim@innovatis.co.kr>:

> Hello
>
> mReadium JSApi.toggle Media Overlay ();
> The method is not play.
>
> locat content
> [
> 12-10 18:43:20.961: I/chromium(10739): [INFO:CONSOLE(0)] "Failed to
> execute 'play' on 'HTMLMediaElement': API can only be initiated by a user
> gesture.", source: file:///android_asset/readium-shared-js/reader.html (0)
> ]
>
>


-- 
*------------------------------*
*INNOVATIS. 김기범*
*E-Mail : gbkim@innovatis.co.kr <bhlee@innovatis.kr>*
* <bhlee@innovatis.kr>**C.P : Tel : 02) 325-2423 / Fax : 02) 324-2427*
*Addr. : **서울시 마포구 잔다리로 73*
*코마빌딩 5층 이노버티스*

**Comment by danielweck** [comment]
Regarding Media Overlays playback, are you able to start audio using the Android launched application "play" button?
PS: it is normal for a mobile browser to ; by default ; prevent automatic media playback / require user input. This is a well-documented issue on the web. Readium includes a special code path to trigger the user gesture capture and prepare the HTML5 audio element (to make it ready for playback). But as far as I remember it is only necessary in iOS. See touchInit() in audio_player.js
