### ISSUE TITLE
Boost third-party lib deprecation (std::regex)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-sdk#231]
Headers and prebuilt static libs:
https://github.com/readium/readium-sdk/tree/develop/ePub3/ThirdParty/boost

Source code:
https://github.com/readium/Boost-for-Android

See README:
https://github.com/readium/readium-sdk/blob/develop/ePub3/ThirdParty/boost/lib/README.md

See @clebeaupin change in feature/gradle-experimental:
https://github.com/readium/readium-sdk/commit/a757b704475805e3ea848a70050b61d5b9d66621

**Comment by rkwright** [comment]
Note also there is a repo as well, but it is a fork from https://github.com/MysticTreeGames/Boost-for-Android:

https://github.com/readium/Boost-for-Android

**Comment by danielweck** [comment]
@rkwright I gave this information in the original description (the README also points to the other repos)

**Comment by danielweck** [comment]
Now that Android Studio / Gradle support is in the develop branch, we must revisit this issue (Boost removal?).

**Comment by danielweck** [comment]
TODO: delete the `ePub3/ThirdParty/boost` folder in the develop branch: https://github.com/readium/readium-sdk/tree/develop/ePub3/ThirdParty/boost
See Android-specific removal: https://github.com/readium/readium-sdk/commit/a757b704475805e3ea848a70050b61d5b9d66621

**Comment by danielweck** [comment]
Boost headers and static libs now removed: https://github.com/readium/readium-sdk/commit/ad7d9cd47d6bc7c94a69e71e726d145f8baac9be

**Comment by danielweck** [comment]
@rkwright it looks like you can archive / delete the https://github.com/readium/Boost-for-Android repository.
