### ISSUE TITLE
Readium SDK tutorial for windows

### ISSUE THREAD

**Issue by mahag** [readium/readium-sdk#250]
Can you plz provide me with a clear documentation on how to use readium sdk inside my website developed under microsoft visual studio 2012.
I checked this document [https://docs.google.com/document/d/1DphaTO2fu7mQoBKalzyfphIlOB2Ncp7yHbIbbti92CE/edit](url)

But the part related to windows is empty.

And another question does readium SDK works for website/webpage and not application as mentioned in Readium description

**Comment by danielweck** [comment]
You are in the wrong repository (readium-sdk). This is for native apps.
Please follow the instructions in the readium-js-viewer README:
https://github.com/readium/readium-js-viewer/blob/develop/README.md
