### ISSUE TITLE
How to know when user click a hightlight?

### ISSUE THREAD

**Issue by xieweizhi** [readium/readium-sdk#255]
Is there a way to do this in iOS ?

**Comment by danielweck** [comment]
see https://github.com/readium/readium-js-viewer/blob/develop/src/js/EpubReader.js#L1105


  readium.reader.plugins.highlights.on("annotationClicked", function(type, idref, cfi, id) {
        console.debug("ANNOTATION CLICK: " + id);
                    
                    });

**Comment by danielweck** [comment]
oh, and remember to enable the highlighter plugin in your build configuration:
https://github.com/readium/readium-shared-js/blob/develop/plugins/plugins.cson#L3
