### ISSUE TITLE
Xcode8 build error. (Undefined symbols for architecture arm64)

### ISSUE THREAD

**Issue by kirou** [readium/readium-sdk#264]
An error occurs when building a real machine with Xcode 8.1
I'm using 0.16.0 and 0.23.0.

<img width="405" alt="2016-11-11 15 12 43" src="https://cloud.githubusercontent.com/assets/1872033/20206096/86c035d6-a821-11e6-94b9-20d37934c172.png">

On Xcode 7.1 the build of the real machine was successful.
I was using 0.16.0.

It failed with Xcode8.
However, building with SDKLauncher-iOS of sample will succeed. (0.16.0 and 0.23.0 was successed for Xcode8.)
https://github.com/readium/SDKLauncher-iOS

Therefore, I think that there is something I can not set for my project.
Even though I compare SDKLauncher-iOS with my project, I did not understand where I made a mistake.

Is there any way to solve it?

**Comment by danielweck** [comment]
Just make sure the preprocessor / compiler directive `ENABLE_SYS_CACHE_FLUSH` is false (or not defined), and/or comment out the code, and/or exclude the files from the build.
See:
https://github.com/readium/readium-sdk/issues/248#issue-159512407

Duplicate:
https://github.com/readium/readium-sdk/issues/261

Related:
https://github.com/readium/readium-sdk/issues/257
