### ISSUE TITLE
Per-platform "drop-in" reader component (for iOS, OSX, Android, etc.), lighter-weight than full SDK "launcher" apps

### ISSUE THREAD

**Issue by danielweck** [readium/readium-sdk#265]
Currently, ReadiumSDK users / adopters must implement their application "host" from scratch, or derive it from one of the available app "launchers" which are designed specifically for Android, iOS, OSX.
There is no per-platform "drop-in" reader component that would facilitate the creation of apps with minimal reading system functionality.

Issue originally raised here:
https://github.com/readium/SDKLauncher-iOS/issues/84

**Comment by rkwright** [comment]
Closing as irrelevant in light of Readium-2
