### ISSUE TITLE
【Xcode 8】Strip Linked Product as YES to want to archive successfully

### ISSUE THREAD

**Issue by kirou** [readium/readium-sdk#267]
Archiving with Xcode 8 results in an error.
I'm using 0.16.0 and 0.23.0.

<img width="851" alt="error" src="https://cloud.githubusercontent.com/assets/1872033/20833779/c43dfdbc-b8d4-11e6-9037-304a370ddd2c.png">  

Succeeded when setting 「Strip Linked Product」 to NO with reference to https://github.com/readium/readium-sdk/issues/261
If possible, I would like to know how to succeed with 「Strip Linked Product」 YES.

I tried https://github.com/readium/readium-sdk/pull/260/files and https://github.com/readium/readium-sdk/issues/261#issuecomment-262789566
, but it did not change and it was an error

Would you please tell me the way the archive passes though Strip Linked Product as YES?

**Comment by danielweck** [comment]
Closing, let's continue the discussion in the original thread:
https://github.com/readium/readium-sdk/issues/261#issuecomment-264523749
