### ISSUE TITLE
How to start with it

### ISSUE THREAD

**Issue by prsolucoes** [readium/readium-sdk#284]
Hi,

I have a prototype to send tomorrow to a possible customer. I need make a small example showing some epubs with cover image and on click, show the epub contents.

I made all in swift, but now im trying show the epub, and on your example i see that you use EPubViewController to show it with a webview opening a connection with a local server. Im trying remake all in swift, but before made the rest, can i reuse this from your package? I trying copying all to my project, but a lot of problem with files with extension .m happen.

How can i show the epub on swift with the c++ SDK?

Thanks for any help. [desesperated]

**Comment by prsolucoes** [comment]
Hi,

Uffa! I have terminated the app. I made everything you do in objc, but in swift3. I have converted all and it is working. Thanks.

**Comment by danielweck** [comment]
I am glad you were able to meet your deadline.
The release tag 0.26 has just been created on the master branch (of every Readium JS /SDK repository), is that what your Swift port is based on?

**Comment by prsolucoes** [comment]
Hi,

I have finished all, thanks. I made a video for you. It is based on other version, but i updated now everything and it is working fine. Dont stop the work on this library, is very nice.

https://www.dropbox.com/s/5u32zevqcbcbgtt/ReaderVideoImplSwift.mov?dl=0

**Comment by danielweck** [comment]
Well done, and thank you for letting us know!
