### ISSUE TITLE
Readium on mac no longer supporting 'rgba' styling on links 

### ISSUE THREAD

**Issue by artbyrt** [readium/readium-sdk#290]
*General Instructions*

- *Please use a short, but meaningful title.*
- *Delete everything in italics before submitting issue*
- *Make sure to fill in as much information as possible*

#### This issue is a Bug|Feature Request|Enhancement|Question|Task|Other
*(choose ONE from the above list and delete the others)*

#### Related issue(s) and/or pull request(s)
*Example: See also #NUMBER*

#### Expected Behaviour
*What you expected Readium to do...*

#### Observed behaviour
*Instead, Readium does...*

#### Steps to reproduce
1. First, do this
2. Then do this
3. etc.

#### Test file(s)
*If relevant, please indicate public EPUB URL(s), or whether you can share ebook(s) privately.  It is often next to impossible to reproduce bugs without the original file.*

### Product
*Choose one of the following (and delete the others)*

* Readium Chrome extension
  * latest official version available from the Chrome Web Store 
  * Version of the Chrome browser
  * OS and version
* Readium cloud reader app
  * latest development build uploaded at https://readium.firebaseapp.com OR a custom integration (list public deployment URL, if any)
  * Browser and version
  * OS and version
* Native application (Readium SDK C++)
  * official "launcher" sample OR propietary app
  * OS and version
* Hybrid app (ReadiumJS)
  * Electron OR Apache Cordova OR ?
  * OS and version
* Other?

#### Additional information
*Please list any additional information that might help us*

**Comment by artbyrt** [comment]
This issue is a Bug
Expected Behaviour: the test sampler book has ‘rgba’ styles on links which are being ignored - a substitute opaque teal colour is being used.

download link for book is at: http://artbyrt.com/rt/tht-epub3.html

sample css :
p.return a:link {
	font-size: .89em;
	color: rgba(117, 19, 0, .8);
	padding: .3em;
}

p.return a:hover {
	background-color: rgba(26, 130, 148, .2);
	border-radius: 5px;
}

These colours are being ignored by newest Readium (earlier version did display as instructed.

Readium Chrome extension
version ?? [the ‘about’ menu selection is greyed out]
OS 10.10.5 Yosemite

Browser and version
Chrome Version 58.0.3029.110 (64-bit)
OS 10.10.5

**Comment by danielweck** [comment]
Duplicate: https://github.com/readium/readium-sdk/issues/291
