### ISSUE TITLE
Newest version of Readium is ignoring 'rgba' styling

### ISSUE THREAD

**Issue by artbyrt** [readium/readium-sdk#291]
This issue is a Bug
Expected Behaviour: the test sampler book has ‘rgba’ styles on links which are being ignored - a substitute opaque teal colour is being used.

download link for book is [at:](http://artbyrt.com/rt/tht-epub3.html)

sample css :
```
p.return a:link {
	font-size: .89em;
	color: rgba(117, 19, 0, .8);
	padding: .3em;
}

p.return a:hover {
	background-color: rgba(26, 130, 148, .2);
	border-radius: 5px;
}

```
These colours are being ignored by newest Readium (earlier version did display as instructed.

Readium Chrome extension
version ?? [the ‘about’ menu selection is greyed out]
OS 10.10.5 Yosemite

Browser and version
Chrome Version 58.0.3029.110 (64-bit)
OS 10.10.5

**Comment by danielweck** [comment]
Thank you for reporting this. Please open the "settings" dialog in the Readium Chrome app (hit the `o` key or click on the top-right icon in the toolbar), under the heading "TEXT AND BACKGROUND COLOR" choose "Default (authors styles)". Let me know if this doesn't work. Regards, Daniel

**Comment by artbyrt** [comment]
worked. 
Thanks.

<((:-) …LOL….  (-:))>
-----------------------
The possible's slow fuse is lit by the Imagination. –Emily Dickinson


ruth tait
http://www.artbyrt.com
O: 416 900 5631

**Comment by danielweck** [comment]
By the way, I am not sure how the "formatted for Readium" version differs from the "iBooks" EPUB, but both seem to load just fine with the latest web/cloud reader (be a little patient, it usually takes a while to load):

**TheHoneyedTale.epub default (iBooks)**:
https://readium.firebaseapp.com/?epub=https%3A%2F%2Fcors-anywhere.herokuapp.com%2Fhttp%3A%2F%2Fartbyrt.com%2Fartbyrt_downloads%2FTheHoneyedTale.epub

**The Honeyed Tale.epub formatted for Readium**:
https://readium.firebaseapp.com/?epub=https%3A%2F%2Fcors-anywhere.herokuapp.com%2Fhttp%3A%2F%2Fartbyrt.com%2Fartbyrt_downloads%2Fepub_Readium%2FTheHoneyedTale.epub

Thanks anyway! :)

**Comment by artbyrt** [comment]
The only format difference is the ‘footnote’ return to text anchor tag added (since ibooks uses it’s own proprietary pop-up for footnotes (which I hate!!)

<((:-) …LOL….  (-:))>
-----------------------
The possible's slow fuse is lit by the Imagination. –Emily Dickinson


ruth tait
http://www.artbyrt.com
O: 416 900 5631
