### ISSUE TITLE
Available Android Apps based on Readium?

### ISSUE THREAD

**Issue by hatton** [readium/readium-sdk#309]
We ([Bloom](bloomlibrary.org)) are [beginning a project](https://allchildrenreading.org/challenge/book-boost-access-challenge/) to lower the bar for creating "born accessible" epubs. Our focus is on making it easy to create epubs for people with visual limitations who speak the world's minority languages, which lack TTS systems. Instead of relying on TTS, we make it [easy to make voice recordings](https://www.youtube.com/watch?v=5M3nJrlf3p0) of the text.

We have always struggled to find epub 3-compliant apps to recommend to use the epubs we produce; gitden is the only one we can even partially recommend. Now that we will be adding audio image descriptions (perhaps the first to try that?), it is only going to get more difficult.

Enter Readium, which we ship as part of the Bloom Editor for previewing epubs. It is the most standards-compliant system we know of. And great, I see that you produce a library for use on Android. But we don't have the resources to be in the business of publishing our own epub reader based on it.

So finally, to my question: can anyone help us find Android apps that use this Readium SDK?

Thanks so much.

**Comment by llemeurfr** [comment]
On Android, using the Readium SDK, I can list : Bookari ebook Reader, Bluefire Reader. 
And in the coming months, using the new Readium-2 SDK (a new generation), you should find Lisa Reader, Aldiko Book Reader, and I hope many more including SimplyE, the NYPL reader.

**Comment by hatton** [comment]
Super, thanks @llemeurfr.
