### ISSUE TITLE
Is this project still actively maintained?

### ISSUE THREAD

**Issue by HppZ** [readium/readium-sdk#321]
I want to use this sdk in my windows 10 UWP project.

**Comment by danielweck** [comment]
Hello, there have been prior efforts to create a Windows-compatible build configuration (Win32, WinRT, and also UWP), but as far as I know this hasn't been maintained for a long time.
I cannot remember exactly, but here are related Pull Requests:
https://github.com/readium/readium-sdk/pull/192
https://github.com/readium/readium-sdk/pull/124

Personally I have been maintaining the build configurations for Android and iOS, in this PR:
https://github.com/readium/readium-sdk/pull/317

**Comment by HppZ** [comment]
Hi, Why not make it happen, Windows is great and UWP is great. There is no good epub reader on Windows, the legacy Edge was good, but it is not available since Windows 1909, so I want to create a epub app using Xaml, but I need a good epub parser, so I found readium-sdk, could you please please please support Windows platform?

**Comment by llemeurfr** [comment]
> There is no good epub reader on Windows

At EDRLab we're very actively developing [Thorium Reader  ](https://www.edrlab.org/software/thorium-reader/) as a "good epub reader on Windows" + MacOS + Linux. We chose Electron to be cross-platform. 

 > could you please please please support Windows platform?

Readium is a community, not a company. The c++ epub parser included in the Readium SDK works well, for several years. Making sure is compiles well and can be UWP wrapped for modern Windows build systems is in your hands. If you decide to do that, a gift to the community would be appreciated.

**Comment by danielweck** [comment]
Hello again, this is an open-source project, so anybody is welcome to fork the codebase and propose feature extensions / improvements :)
That being said, I personally believe the effort required to bridge the C++ code with the UWP framework would be costly, and (in my opinion) not justified.
There is more active Readium development in platform-native code (e.g. Android-Kotlin, iOS-Swift), and as Laurent said in his comment above, there is also a cross-platform Electron-based implementation of the same Readium architecture.

**Comment by HppZ** [comment]
Thanks for all your reply.

I tried Thorium Reader, and an error occured.
![Uploading image.png…]()

**Comment by HppZ** [comment]
![image](https://user-images.githubusercontent.com/12285582/75030997-41b4d900-54e0-11ea-9a10-5557108d1be1.png)

**Comment by HppZ** [comment]
is it trying to connect to internet?

**Comment by danielweck** [comment]
This bug [was fixed](https://github.com/readium/readium-desktop/commit/4bbf830e0ac7199bc2d21d289f1337b01e031f83) after version `1.1.1` was released, could you please try again with a more recent build from: https://github.com/readium/readium-desktop/releases/
Thank you!

**Comment by HppZ** [comment]
current is v1.1.1

![image](https://user-images.githubusercontent.com/12285582/75032544-ca814400-54e3-11ea-81df-4537d613fb7a.png)

**Comment by danielweck** [comment]
Yes, please try `[latest-windows] continuous test build (prerelease)`

**Comment by HppZ** [comment]
oh works fine.

**Comment by llemeurfr** [comment]
Note that this discussion about Thorium bugs has nothing to do in the readium-sdk area :-)

**Comment by llemeurfr** [comment]
so, shall we close this issue now?
