### ISSUE TITLE
Highlight does not work

### ISSUE THREAD

**Issue by sajjadrad** [readium/readium-sdk#40]
Hi
I cloned develop branch and used highlight api in iOS SDK launcher,but nothing happens.
getCurrentSelectionCfi function returns null,addSelectionHighlight do nothing after select a text.
I used this code in a button click event:
```
    NSString *result = [m_webView stringByEvaluatingJavaScriptFromString:@"ReadiumSDK.reader.getCurrentSelectionCfi()"];
    NSLog(@"cfi=%@",result);
    [m_webView stringByEvaluatingJavaScriptFromString:@"ReadiumSDK.reader.addSelectionHighlight(124, \"highlight\")"];

```

**Comment by sha256** [comment]
Actually it's working great! You just need to stringify the  return value from JS like:
`JSON.stringify(this.getCurrentSelectionCfi())`
