### ISSUE TITLE
Build error on Visual Studio 2013 for Windows

### ISSUE THREAD

**Issue by ohizumi** [readium/readium-sdk#52]
Hello,

I'm trying to use readium sdk for Windows(readium-sdk-master.zip),
but any build errors on VC2013 output below.
Could you tell me what kind of problem can be considered? 

And,i would like to know zip version is supported now.
if it is not supported, which version we used?  

---------------------------------------------------------------------------------------------------------
-Error 1
c:\program files\microsoft visual studio 12.0\vc\include\xrefwrap(58): error C2064: term does not evaluate to a function taking 2 arguments (..\..\..\..\ePub3\ePub\container.cpp)
-Error 2
readium-sdk-master\epub3\epub\font_obfuscation.cpp(93): error C3861: '_THROW_LAST_ERROR_': identifier not found
-Error 3
readium-sdk-master\epub3\thirdparty\google-url\base\logging.cc(337): error C2084: function 'logging::LogMessage::LogMessage(const char *,int,logging::LogSeverity,int)' already has a body
-Error 4
readium-sdk-master\epub3\thirdparty\google-url\base\logging.cc(452): error C2228: left of '.stream' must have class/struct/union
...
---------------------------------------------------------------------------------------------------------

Best Regards,

**Comment by danielweck** [comment]
@rkwright is successfully testing the SDKLauncher-Windows, see this branch:
https://github.com/readium/SDKLauncher-Windows/tree/feature/feature_revised_launcher

**Comment by rakanmatouq** [comment]
@danielweck  but i want the SDKLauncher for android not windows :)
