### ISSUE TITLE
Android Gradle build

### ISSUE THREAD

**Issue by Twibit** [readium/readium-sdk#62]
Hi, 

Is it possible to add a gradle build script to the android project ?
It'll allow us to add readium-sdk as a library in gradle powered projects.

Here is mine : https://gist.github.com/ClementH/a3aa8c26ac2015af5703

**Comment by danielweck** [comment]
The old Eclipse model is deprecated (by Google), now replaced with Android Studio IDE +Gradle build system (with support for hybrid JDK (Java app) / NDK (C++ ReadiumSDK) ). The pull requests have been merged into the develop branch.
