### ISSUE TITLE
Method for get cover from ePub for android

### ISSUE THREAD

**Issue by TienHai** [readium/readium-sdk#68]
Hi, 

I post last day one issue for ask how I can get the cover of ePub.
https://github.com/readium/readium-sdk/issues/66

I want use readium for read ePub, but for more user friendly I want display cover of ePub in a list.

I see in sdk, in package.cpp file the method "ManifestItemsWithProperties", but can't call from java side. I wrote the jni part for call this method.
In fact I don't call the native method in package.cpp, because I don't know instanciate some object need. I rewrite one.

Please, can you add this method or another better for get cover ?
# 

In my project, In my file java, I open a ePub and get the cover

// Open ePub
Container container = EPub3.openBook(path);
// Get package
Package pckg = container.getDefaultPackage();

```
            // Get the cover
            String filename = "cover";
            String cache_dir = "Covers";
            File dir = new File(context.getExternalCacheDir(), cache_dir);
            if ( !dir.exists() )
                dir.mkdir();

            List<ManifestItem> items = pckg.GetManifestItemsWithProperties("cover-image");
            if ( !items.isEmpty() )
            {
                ManifestItem coverItm = items.get(0);

                String extension = "";
                if ( coverItm.getMediaType().equals("image/jpeg") )
                    extension = ".jpg";
                else if (coverItm.getMediaType().equals("image/png"))
                    extension = ".png";

                byte[] data = pckg.getContent(coverItm.getHref());

                FileOutputStream out;
                try {
                    out = new FileOutputStream(context.getExternalCacheDir()+"/"+cache_dir+"/"+filename+extension);
                    out.write(data);
                    out.close();

                } catch (FileNotFoundException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                } catch (IOException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }      
            }
```
# 

File readium-sdk/Platform/Android/src/org/readium/sdk/android/Package.java

```
public List<ManifestItem> GetManifestItemsWithProperties(String properties) {
    List<ManifestItem> lst = nativeGetManifestItemsWithProperties(__nativePtr, properties);
    return lst;
}

private native List<ManifestItem> nativeGetManifestItemsWithProperties(long nativePtr, String properties);
```
# 

File readium-sdk/Platform/Android/jni/package.cpp I had this method

JNIEXPORT jobject JNICALL Java_org_readium_sdk_android_Package_nativeGetManifestItemsWithProperties
        (JNIEnv\* env, jobject thiz, jlong pckgPtr, jstring jProperties) 
{  
    ePub3::ManifestTable manifest = PCKG(pckgPtr)->Manifest();
    jobject manifestItemList = env->CallStaticObjectMethod(javaJavaObjectsFactoryClass,
            createManifestItemList_ID);

```
char *properties = (char *) env->GetStringUTFChars(jProperties, NULL);
///LOGD("ManifestItem: property : %s", property);

for (auto i = manifest.begin(); i != manifest.end(); i++) {
    std::shared_ptr<ePub3::ManifestItem> item = i->second;

    if ( item->HasProperty(properties) ) {
        jni::StringUTF hr(env, (std::string&) item->Href().stl_str());
        jstring href = (jstring) hr; 
        jni::StringUTF mt(env, (std::string&) item->MediaType().stl_str());
        jstring mediaType = (jstring) mt;

        jobject manifestItem = env->CallStaticObjectMethod(javaJavaObjectsFactoryClass, createManifestItem_ID,
                href, mediaType);    

        env->CallStaticVoidMethod(javaJavaObjectsFactoryClass, addManifestItemToList_ID,
                manifestItemList, manifestItem);
        env->DeleteLocalRef(href);
        env->DeleteLocalRef(mediaType);
        env->DeleteLocalRef(manifestItem);
    }
}

return manifestItemList;
```

}
# 

File readium-sdk/Platform/Android/jni/package.h I had this

JNIEXPORT jobject JNICALL Java_org_readium_sdk_android_Package_nativeGetManifestItemsWithProperties
        (JNIEnv\* env, jobject thiz, jlong pckgPtr, jstring jProperties);

Thanks, and hope help someone.

**Comment by danielweck** [comment]
Actually, instead of querying `cover-image`, better use the built-in function:
https://github.com/readium/readium-sdk/blob/80a71fedf03f6f11ba7f900daf0ac67675388908/ePub3/ePub/package.cpp#L1682

**Comment by danielweck** [comment]
Also see: https://github.com/readium/SDKLauncher-iOS/issues/96
