### ISSUE TITLE
readium-sdk (0.7 or 0.14 or any version) build warning

### ISSUE THREAD

**Issue by yuch1001** [readium/readium-sdk#69]
Hi, I'm Android Developer from korea.
i'm using this library, to make my "EPUB Reader".
so see guide doc, follow that.
(refer:  https://docs.google.com/a/drminside.com/document/d/1DphaTO2fu7mQoBKalzyfphIlOB2Ncp7yHbIbbti92CE/edit#)

and i have a question.

In Android ver,
when i build sdk in mac(mavericks ver.10.9.4), then Boom! i have a warnings.
next is part of text when building:

----------------------------------------------------------------------------------------------------------------

[armeabi-v7a] Compile++ thumb: epub3 <= base.cpp
/Library/developer/android-ndk-r9d/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86/bin/arm-linux-androideabi-g++ -MMD -MP -MF ./jni/obj/local/armeabi-v7a/objs-debug/epub3/ePub3/xml/utilities/base.o.d -fpic -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -fno-exceptions -fno-rtti -mthumb -Os -g -DNDEBUG -fomit-frame-pointer -fno-strict-aliasing -finline-limit=64 -O0 -UNDEBUG -marm -fno-omit-frame-pointer -Iinclude -I./../../ePub3 -I./../../ePub3/utilities -I./../../ePub3/xml -I./../../ePub3/xml/tree -I./../../ePub3/xml/utilities -I./../../ePub3/xml/validation -I./../../ePub3/ePub -I./../../Platform/Android/jni -I./../../Platform/Android/jni/android -I./../../ePub3/ThirdParty/openssl-android/include -I./../../ePub3/ThirdParty/boost/include -I/Library/developer/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include -I/Library/developer/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a/include -I/Library/developer/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/backward -I./../../ePub3/ThirdParty/icu4c/include -I./../../ePub3/ThirdParty/icu4c/include -I./../../ePub3/ThirdParty/icu4c/include -I./../../ePub3/ThirdParty/icu4c/include -I./../.. -DANDROID -std=gnu11 -include prefix.h -DBUILDING_EPUB3 -Wa,--noexecstack -Wformat -Werror=format-security -std=gnu++11 -include prefix.h -fpermissive -DBUILDING_EPUB3 -frtti -fexceptions -std=gnu++11 -include prefix.h -fpermissive -DBUILDING_EPUB3    -I/Library/developer/android-ndk-r9d/platforms/android-9/arch-arm/usr/include -c  ./../../ePub3/xml/utilities/base.cpp -o ./jni/obj/local/armeabi-v7a/objs-debug/epub3/ePub3/xml/utilities/base.o 
cc1plus: warning: command line option '-std=gnu11' is valid for C/ObjC but not for C++ [enabled by default]
In file included from include/ePub3/xml/document.h:24:0,
                 from ./../../ePub3/xml/utilities/base.cpp:22:
include/ePub3/xml/node.h:97:41: warning: declaration of 'std::shared_ptr<ePub3::xml::Namespace> ePub3::xml::Node::Namespace() const' [-fpermissive]
  std::shared_ptr<Namespace> Namespace() const;
                                                                        ^(on const)
In file included from include/ePub3/xml/node.h:25:0,
                 from include/ePub3/xml/document.h:24,
                 from ./../../ePub3/xml/utilities/base.cpp:22:
include/ePub3/xml/ns.h:47:7: warning: changes meaning of 'Namespace' from 'class ePub3::xml::Namespace' [-fpermissive]
 class Namespace : public WrapperBase<Namespace>
          ^(on Namespace)
In file included from include/ePub3/xml/document.h:24:0,
                 from ./../../ePub3/xml/utilities/base.cpp:22:
include/ePub3/xml/node.h:149:40: warning: declaration of 'std::shared_ptr<ePub3::xml::Document> ePub3::xml::Node::Document()' [-fpermissive]
     std::shared_ptr<Document> Document();
                                                                   ^(on ')' )
In file included from include/ePub3/xml/node.h:25:0,
                 from include/ePub3/xml/document.h:24,
                 from ./../../ePub3/xml/utilities/base.cpp:22:
include/ePub3/xml/ns.h:34:7: warning: changes meaning of 'Document' from 'class ePub3::xml::Document' [-fpermissive]
 class Document;
          ^(on Document)

----------------------------------------------------------------------------------------------------------------

not only this.
this is first of many warnings.

Almost about "const" word or class's name's meaning declaration

and about command line option "-std=gnu11"

----------------------------------------------------------------------------------------------------------------

[armeabi-v7a] Compile++ thumb: epub3 <= error_handler.cpp
/Library/developer/android-ndk-r9d/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86/bin/arm-linux-androideabi-g++ -MMD -MP -MF ./jni/obj/local/armeabi-v7a/objs-debug/epub3/ePub3/utilities/error_handler.o.d -fpic -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -fno-exceptions -fno-rtti -mthumb -Os -g -DNDEBUG -fomit-frame-pointer -fno-strict-aliasing -finline-limit=64 -O0 -UNDEBUG -marm -fno-omit-frame-pointer -Iinclude -I./../../ePub3 -I./../../ePub3/utilities -I./../../ePub3/xml -I./../../ePub3/xml/tree -I./../../ePub3/xml/utilities -I./../../ePub3/xml/validation -I./../../ePub3/ePub -I./../../Platform/Android/jni -I./../../Platform/Android/jni/android -I./../../ePub3/ThirdParty/openssl-android/include -I./../../ePub3/ThirdParty/boost/include -I/Library/developer/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include -I/Library/developer/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a/include -I/Library/developer/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include/backward -I./../../ePub3/ThirdParty/icu4c/include -I./../../ePub3/ThirdParty/icu4c/include -I./../../ePub3/ThirdParty/icu4c/include -I./../../ePub3/ThirdParty/icu4c/include -I./../.. -DANDROID -std=gnu11 -include prefix.h -DBUILDING_EPUB3 -Wa,--noexecstack -Wformat -Werror=format-security -std=gnu++11 -include prefix.h -fpermissive -DBUILDING_EPUB3 -frtti -fexceptions -std=gnu++11 -include prefix.h -fpermissive -DBUILDING_EPUB3    -I/Library/developer/android-ndk-r9d/platforms/android-9/arch-arm/usr/include -c  ./../../ePub3/utilities/error_handler.cpp -o ./jni/obj/local/armeabi-v7a/objs-debug/epub3/ePub3/utilities/error_handler.o 

cc1plus: warning: command line option '-std=gnu11' is valid for C/ObjC but not for C++ [enabled by default]

----------------------------------------------------------------------------------------------------------------

and unknown

----------------------------------------------------------------------------------------------------------------

(^ is all on end of text)
In file included from ./../../ePub3/utilities/error_handler.cpp:21:0:
./../../ePub3/utilities/error_handler.h:517:52: warning: '__visibility__' attribute ignored [-Wattributes]
 void __DispatchError(const std::system_error& __err)
                                                                                    ^
./../../ePub3/utilities/error_handler.h:523:50: warning: '__visibility__' attribute ignored [-Wattributes]
 void __DispatchError(const epub_spec_error& __err)
                                                                                    ^
./../../ePub3/utilities/error_handler.h:530:62: warning: '__visibility__' attribute ignored [-Wattributes]
 void HandleError(int __code, const std::error_category& __cat)
                                                                                                   ^
./../../ePub3/utilities/error_handler.h:536:88: warning: '__visibility__' attribute ignored [-Wattributes]
 void HandleError(int __code, const std::error_category& __cat, const std::string& __msg)
          ^
./../../ePub3/utilities/error_handler.h:542:81: warning: '__visibility__' attribute ignored [-Wattributes]
 void HandleError(int __code, const std::error_category& __cat, const char* __msg)
                                                                                                                                  ^
./../../ePub3/utilities/error_handler.h:548:34: warning: '__visibility__' attribute ignored [-Wattributes]
 void HandleError(std::errc __code)
                                                       ^
./../../ePub3/utilities/error_handler.h:554:60: warning: '__visibility__' attribute ignored [-Wattributes]
 void HandleError(std::errc __code, const std::string& __msg)
                                                                                               ^
./../../ePub3/utilities/error_handler.h:560:53: warning: '__visibility__' attribute ignored [-Wattributes]
 void HandleError(std::errc __code, const char* __msg)
                                                                                      ^
./../../ePub3/utilities/error_handler.h:566:34: warning: '__visibility__' attribute ignored [-Wattributes]
 void HandleError(EPUBError __code)
                                                          ^
./../../ePub3/utilities/error_handler.h:572:60: warning: '__visibility__' attribute ignored [-Wattributes]
 void HandleError(EPUBError __code, const std::string& __msg)
                                                                                                   ^
./../../ePub3/utilities/error_handler.h:578:53: warning: '__visibility__' attribute ignored [-Wattributes]
 void HandleError(EPUBError __code, const char* __msg)
                                                                                          ^

----------------------------------------------------------------------------------------------------------------

next is maybe occur in file that using spine.h

----------------------------------------------------------------------------------------------------------------

In file included from ./../../ePub3/ePub/package.h:32:0,
                 from ./../../ePub3/ePub/container.cpp:21:
include/ePub3/spine.h:132:53: warning: declaration of 'std::shared_ptr<ePub3::ManifestItem> ePub3::SpineItem::ManifestItem() const' [-fpermissive]
     shared_ptr<ManifestItem>    ManifestItem()      const;
                                                                              ^(on const)
In file included from include/ePub3/epub3.h:33:0,
                 from ./../../ePub3/ePub/package.h:24,
                 from ./../../ePub3/ePub/container.cpp:21:
include/ePub3/Forward.h:38:21: warning: changes meaning of 'ManifestItem' from 'class ePub3::ManifestItem' [-fpermissive]
 _EPUB_DECLARE_CLASS(ManifestItem);
                                             ^(on ManifestItem)
include/ePub3/Forward.h:30:7: note: in definition of macro '_EPUB_DECLARE_CLASS'
 class name; \
          ^(on name)
In file included from ./../../ePub3/ePub/container.cpp:21:0:
./../../ePub3/ePub/package.h:222:80: warning: declaration of 'std::shared_ptr<ePub3::NavigationTable> ePub3::PackageBase::NavigationTable(const ePub3::string&) const' [-fpermissive]
     shared_ptr<NavigationTable> NavigationTable(const string& type)            const;
                                                                                                                         ^(on const)
./../../ePub3/ePub/package.h:51:7: warning: changes meaning of 'NavigationTable' from 'class ePub3::NavigationTable' [-fpermissive]
 class NavigationTable;
           ^(on NavigationTable)
In file included from ./../../ePub3/ePub/container.cpp:21:0:
./../../ePub3/ePub/package.h:315:115: warning: declaration of 'std::shared_ptr<ePub3::MediaOverlaysSmilModel> ePub3::PackageBase::MediaOverlaysSmilModel() const' [-fpermissive]
     std::shared_ptr<MediaOverlaysSmilModel>    MediaOverlaysSmilModel()      const       { return _mediaOverlays; }
                                                                                                                             ^(on const)
In file included from ./../../ePub3/ePub/container.cpp:21:0:
./../../ePub3/ePub/package.h:56:7: warning: changes meaning of 'MediaOverlaysSmilModel' from 'class ePub3::MediaOverlaysSmilModel' [-fpermissive]
 class MediaOverlaysSmilModel;
           ^(on MediaOverlaysSmilModel)
In file included from ./../../ePub3/ePub/container.cpp:21:0:
./../../ePub3/ePub/package.h:317:60: warning: declaration of 'std::shared_ptr<ePub3::Archive> ePub3::PackageBase::Archive() const' [-fpermissive]
     shared_ptr<Archive> Archive() const { return _archive; }
                                                                                            ^(on end of text)
In file included from include/ePub3/archive_xml.h:26:0,
                 from ./../../ePub3/ePub/package.h:36,
                 from ./../../ePub3/ePub/container.cpp:21:
include/ePub3/archive.h:52:7: warning: changes meaning of 'Archive' from 'class ePub3::Archive' [-fpermissive]
 class Archive
       ^(on Archive)
In file included from include/ePub3/content_module.h:25:0,
                 from ./../../ePub3/ePub/container.h:29,
                 from ./../../ePub3/ePub/container.cpp:22:
include/ePub3/user_action.h:63:79: warning: declaration of 'virtual const ePub3::IRI& ePub3::UserAction::IRI() const' [-fpermissive]
     const IRI&           IRI()          const _NOEXCEPT FINAL { return m_iri; }
                                                                                                                ^(on end of text)
In file included from include/ePub3/property.h:27:0,
                 from include/ePub3/property_holder.h:26,
                 from include/ePub3/spine.h:27,
                 from ./../../ePub3/ePub/package.h:32,
                 from ./../../ePub3/ePub/container.cpp:21:
include/ePub3/utilities/iri.h:43:7: warning: changes meaning of 'IRI' from 'class ePub3::IRI' [-fpermissive]
 class IRI
          ^(on IRI)
In file included from include/ePub3/content_module.h:26:0,
                 from ./../../ePub3/ePub/container.h:29,
                 from ./../../ePub3/ePub/container.cpp:22:
include/ePub3/utilities/future.h:3529:1: warning: always_inline function might not be inlinable [-Wattributes]
 ____make_future_deferred_shared_state(_Fp&& __f)
 ^(on start of text)
include/ePub3/utilities/future.h:3537:1: warning: always_inline function might not be inlinable [-Wattributes]
 ____make_future_async_shared_state(_Fp&& __f)
 ^(on start of text)

----------------------------------------------------------------------------------------------------------------

and meaning change problem occur also Forward.h about "ManifestItem"

----------------------------------------------------------------------------------------------------------------

warnings
1. changes meaning of [class Name] from [class full name (ex) ePub3::Archive))] [-fpermissive]
2. '____visibility____' attribute ignored [-Wattributes]
3. declaration of [ex) std::shared_ptr<ePub3::xml::Namespace> ePub3::xml::Node::Namespace() const] [-fpermissive]]

----------------------------------------------------------------------------------------------------------------

in result, be made libepub3.so file.
but i use that file in windows, eclipse.(also mac)
and then run in smart phone.
Reader read metadata but i can't see any texts or pics.
i have no idea what is problem.
warning occuring is normal? or am i change settings about something?

i wanna answer for this problem!
PLEASE ANSWER TO ME, PLEASE.

and when use sdk, shared-js, launcher, have to use same version? in this time, i use same version...

and what is this text?

Android NDK: WARNING:Android.mk:xml2: LOCAL_LDLIBS is always ignored for static libraries

is it ok?

----------------------------------------------------------------------------------------------------------------

and android debugging in logcat.

org.readium.sdk.android.launcher <s3dReadConfigFile:75>: Can't open file for reading

SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length

Package.nativeReadStreamForRelativePath() : no archive found for path 

'EPUB/lib/jquery-1.11.0.js'
'EPUB/lib/jquery,sizes.js'
'EPUB/lib/underscore.min.js'
'EPUB/lib/backbone.min.js'

etc...

Web Console

Uncaught ReferenceError: ReadiumSDK is not defined:22
Uncaught ReferenceError: $ is not defined:45
Uncaught ReferenceError: $ is not defined:1

and i can't see anything in app.

**Comment by danielweck** [comment]
You can ignore the warnings.
Please use the latest code from the `master` or `develop` branch, and make sure to initialise and update the submodules in https://github.com/readium/SDKLauncher-Android
It looks like you are missing files.
I am closing the issue, but please feel free to re-open if necessary, and I will be watching this discussion thread.
