### ISSUE TITLE
 Media Overlays, User Interface controls + user preferences

### ISSUE THREAD

**Issue by rkwright** [readium/readium-sdk#71]
See:
https://groups.google.com/forum/#!msg/readium-sdk-contrib/qe3l3Cmb5DQ/jk8bF2-VPiwJ

1) MO optionsUI (via the existing upper-right callout, or a supplementary one?)

1.1) Toggle button "touch-to-play" (on by default)
1.2) Volume slider 0-100% (full by default)
1.3) Rate slider 0-4x (1x by default)
1.4) Toggle button "skippability" (on by default)
1.5) Toggle button "escapability" (on by default)

All of the above must be wired to the existing preferences mechanism, but "doNotRefreshView" must be set to avoid resetting ongoing MO playback due to PAGE_LOAD events in the WebView. See this example:

{
  "fontSize" : UINT,
  "columnGap" : UINT,
  "isSyntheticSpread" : BOOL,
  
  "doNotUpdateView" : BOOL,  

  "mediaOverlaysEnableClick" : BOOL,

  "mediaOverlaysVolume" : DOUBLE_0-100,
  "mediaOverlaysRate" : DOUBLE_0-4

  "mediaOverlaysSkipSkippables" : BOOL,
  "mediaOverlaysSkippables" : STRING-COMMA-SEPARATED,

  "mediaOverlaysEscapeEscapables" : BOOL,
  "mediaOverlaysEscapables" : STRING-COMMA-SEPARATED,
}

2) Navigation user interface (inside existing bottom navigation bar ?)

2.1) Play/Pause button (single button, two states)
JS ==> ReadiumSDK.reader.toggleMediaOverlay()

2.2) Previous / Next buttons (phrase-level navigation)
JS ==> ReadiumSDK.reader.nextMediaOverlay() ReadiumSDK.reader.previousMediaOverlay()

2.3) Escape button
JS ==> ReadiumSDK.reader.previousMediaOverlay()

I suggest we put a higher priority on #2, which mostly consists in executing single-line Javascript commands (shown above). Launcher-iOS also has to listen to the "is-MO-playing" WebView-emitted event, to refresh the play/pause button state. This event's payload consists in a small data set, and in Launcher-iOS we only care about the "isPlaying" field (unlike the OSX app which has a more sophisticated playback timeline scrubbing bar).

(Note:  Transferred from Bugzilla, #10, 24 July 2014).

**Comment by danielweck** [comment]
This was addressed some time ago. Closing.
