### ISSUE TITLE
 Support for Kitkat 4.4 ART (not Dalvik)

### ISSUE THREAD

**Issue by rkwright** [readium/readium-sdk#75]
(This is transferred from Bugzilla Bug #19, 28 July 2014)

Logged by  Daniel Weck 2013-11-28 02:55:44 CST

http://source.android.com/devices/tech/dalvik/art.html
ART is an opt-in experimental feature in 4.4, so this is a low-priority issue.

**Comment by danielweck** [comment]
No problems on my KitKat ART -enabled device.
