### ISSUE TITLE
Compilation error in SDK in async code

### ISSUE THREAD

**Issue by rkwright** [readium/readium-sdk#87]
(Transferred from Bugzilla, bug 72, 28 July 2014)
 Ric Wright 2014-04-22 09:01:31 CDT
Platform: Windows

The code in question is  in \readium-sdk\platform\windows\include\epub3\util
ities\invoke.h(232).

See thread here:

https://groups.google.com/forum/?fromgroups#!searchin/readium-dev/async|sort:relevance|spell:true/readium-dev/BpbTwhX0Wk4/NY_MehWBN2oJ

**Comment by danielweck** [comment]
Let's close this. The async code for "managed" Windows runtime is not in use, see https://github.com/readium/readium-sdk/issues/115
